### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by sarjo** [jaxon-php/jaxon-core#1]
PHP Parse error:  syntax error, unexpected 'namespace' (T_NAMESPACE) in /public_html/inc/vendor/jaxon-php/jaxon-core/src/Request/Plugin/BrowserEvent.php on line 1

This error occurs , I think it is the version of php so change 5.4 to 5.6 and continues to error.

**Comment by feuzeu** [comment]
Hi, can you please show the code that generated this error?

**Comment by feuzeu** [comment]
Also, make sure you don't have a class in your application named "Namespace".

**Comment by sarjo** [comment]
```
<?php
@session_start();
require ('../inc/vendor/autoload.php');
include_once "../inc/model/user.php";
include_once '../inc/adminActions.php';
if (!isset($_SESSION['xx']))
{
  header("Location: ../#!/login");
}else{
	$user=new user($_SESSION['xx']);
	if ($user->usertype != 3) {
		die('You do not have permission');
	}
}
use Jaxon\Jaxon;
$jaxon = jaxon();
$jaxon->register(Jaxon::CALLABLE_OBJECT, new adminAction());
$jaxon->setOption('js.lib.uri', '../js/jaxon-js/src');
$jaxon->setOption('js.app.minify', true);
$jaxon->processRequest();
?>
```
this code on my pc works , but production is not the only difference is that my pc using php 7 and production  php 5.4

**Comment by feuzeu** [comment]
The above code doesn't call the BrowserEvent class. The error may be in the adminAction class or in when you link javascript events to your UI elements.

**Comment by sarjo** [comment]
adminActions.php
`
<?php
include_once 'model/user.php';
use Jaxon\Response\Response;

class adminAction
{`
public function deleteUser($id)
	{
		$xResponse = new Response();
		$user=new user($id);
		if ($user->destroy())
		{
			$xResponse->toastr->success("User deleted");
			$xResponse->script('$("#content").load("../views/adminUsers.php");');
		}else{
			$xResponse->toastr->error("User has not deleted");
		}
		return $xResponse;	
	}
}
?>

**Comment by sarjo** [comment]
the strange thing is that in my computer run but on the server check that error.
Sorry for my english.

**Comment by sarjo** [comment]
same problem with xajax 

https://openclassrooms.com/forum/sujet/xajax-erreur-a-la-creation-d-une-instance-xajax-81341

solution detail in this post is use another version.

**Comment by feuzeu** [comment]
The solution is to use another version of what? PHP or Xajax?

It seems to me that this issue is related to PHP rather than Jaxon. I see no reason why the BrowserEvent class is called in your code.

If you're using a caching system such as Xcache, try flushing or disabling it.

**Comment by sarjo** [comment]
Solution is upload file in binary mode not in ASCII.
