### ISSUE TITLE
getClass deprecated in Di\Container.php

### ISSUE THREAD

**Issue by victorsamuelmd** [jaxon-php/jaxon-core#102]
Hi, thanks for your work with this library, I'm using it with php 8.1, I get this error when using dependency inyection, the solution appears to change the getClass() to getType() in the line 259.

**Comment by victorsamuelmd** [comment]
Hi, thanks for the bugfix, but the change introduced some strage behavior, I think that the line should be:   
$parameterInstances[] = $this->get($parameter->getType()->getName());
you missed the getName().

**Comment by feuzeu** [comment]
Hi,

According to the [ReflectionType class documentation](https://www.php.net/manual/fr/class.reflectiontype.php), it does not necessarily implements the `getName()` methods. But it implements the `Stringable` interface, so it can automatically be converted to string.
Which strange beheviour have you noticed?

**Comment by feuzeu** [comment]
Hi

I've released a new version of the library with improvements on the DI container.
https://github.com/jaxon-php/jaxon-core/releases/tag/v4.1.0
