### ISSUE TITLE
Domain for Documentation seems down

### ISSUE THREAD

**Issue by Teejer** [jaxon-php/jaxon-core#103]
All the link on the main page don't work. I was hoping to look at the documentation, http://www.jaxon-php.org/en/docs/, but you get a 404. 

I'm a long time xajax user, finally getting around to trying out Jaxon.

**Comment by feuzeu** [comment]
Hi,

Welcome in the Jaxon community. I hope you are going to enjoy using our library.
The website is back online. Sorry for the inconvenience.
