### ISSUE TITLE
Call to undefined function Jaxon\CodeIgniter\Filter\jaxon()

### ISSUE THREAD

**Issue by tom-lp-at** [jaxon-php/jaxon-core#104]
Dear Thierry,
at first : thx for keeping this awesome tool alive....
I migrate a project to CI-4 and hang on the usage of jaxon-php V4 :(
I download your useful "demo-codeigniter" to validate my problem. 
As suggested, i run "composer install" and therefore the current CI-4 is installed and the application did not run at first.
After the change of /public/index.php in your demo to the current version from CI (4.2.6) the Application starts an the same error as in my own Application comes up:
![image](https://user-images.githubusercontent.com/28635763/192659090-d5f685aa-3508-4641-bc26-85b222cc1ec6.png)

Did you have a clue what has changed since your demo is created and how to fix this error?
(i have a view other errors, but one after the other :) )
kr Tom_at_LP

**Comment by feuzeu** [comment]
Hi,

The global functions was moved to the `\Jaxon` namespace.
I forgot to make the change in this file.

It is now fixed: https://github.com/jaxon-php/jaxon-codeigniter/commit/852147b9ff1251f951b99951daf161a0ba9660a8
Here's the new release: https://github.com/jaxon-php/jaxon-codeigniter/releases/tag/v4.0.1

**Comment by tom-lp-at** [comment]
Dear Feuzeu,
thx for your response. I declared it manually and have fixed all others of my issues :)
Primary it was the change of the response that has to rewriten in my code...
One typo is in the update to 4.0.1 :
**_You forgot a semicolon in JaxonConfigFilter on line 9 (after JaxonApp)..._**
The issue is closed.
