### ISSUE TITLE
Reinstate CallableObjects in version 4 possible?

### ISSUE THREAD

**Issue by frameworker2019** [jaxon-php/jaxon-core#109]
Using callable classes instead of instantiated object references are sometimes hard to manage. 
It's all about configuring the runtime context of a class and registering to Jaxon.
The callback solution described [here](https://github.com/jaxon-php/jaxon-core/issues/67) cannot be bound to individual classes rather just globally for all classes which are instantiated by Jaxon. So that's what I understand.

Is there another way to force Jaxon to be using the old way to register object references instead of classes?

**Comment by feuzeu** [comment]
Hi,

If you want to run specific code fora given class, you can either use [hooks](https://www.jaxon-php.org/docs/v4x/features/hooks.html) or [dependency injection](https://www.jaxon-php.org/docs/v4x/features/dependency-injection.html).

Hooks can even be defined only for a given method in your class.

You can also use [annotations](https://www.jaxon-php.org/docs/v4x/annotations/about.html) to make your [hooks](https://www.jaxon-php.org/docs/v4x/annotations/hooks.html) and [dependency injection](https://www.jaxon-php.org/docs/v4x/annotations/di.html) to make your definitions easier.

**Comment by feuzeu** [comment]
When you register an object, it will then be instantiated any time you process a Jaxon request, even when another class is called.

Using the above features, your code will be run anly when necessary.
