### ISSUE TITLE
Problems running most jaxon examples

### ISSUE THREAD

**Issue by MiguelAlfonzo87** [jaxon-php/jaxon-core#112]
Good afternoon everyone. Let me tell you, I have always used xajax, but since it is almost impossible to make it run in PHP 8, I am beginning to see Jaxon. The only examples that worked are hello, aliases and classes. However. In XAJAX I use addScritp() to execute functions in XAJAX from JS, or from JS execute xajax_Nombre_Funcion(); and I don't see that anywhere in JAXON. I also use xajax.getFormValues('FormName') and I can't find it in JAXON either. I have followed examples to call a function from the html with <?php echo rq()->call('Form', rq()->form('#DemoForm')) ?> and seeing the response in the inspect element , I get NULL. I don't understand what is happening. Does anyone know a link where these and many more examples work?

**Comment by feuzeu** [comment]
Hi,

Before asking a question, please do your homework, read the Jaxon documentation.
Jaxon was forked from Xajax more than 10 years ago. You cannot expect today to have the exact same functions with the exact same behavior. That's insane.
You have not even upgraded to the latest version of Xajax Jaxon was forked from. That means you need some extra effort to get uptodate.
