### ISSUE TITLE
Question on invalid request

### ISSUE THREAD

**Issue by nevtag** [jaxon-php/jaxon-core#12]
Hi Thierry,
thank you for the hint with alias for synchronous and asynchronous calls, that was a good one.

How can I handle this error?
"Uncaught Jaxon\Exception\Error: Invalid function request received"
I tried it with
`$this->jaxon->register(Jaxon::PROCESSING_EVENT, Jaxon::PROCESSING_EVENT_INVALID, array( $this, 'error_handler') );`
in front of
`$this->jaxon->processRequest();`
But that doesn't work.

regards,
Joc

**Comment by feuzeu** [comment]
Hi Joc,
There's an issue in Jaxon, the invalid event is not handled correctly.
You can use this as a workaround until the issue is fixed.

```php
    try
    {
        $jaxon->processRequest();
    }
    catch(Exception $e)
    {
        $xResponse = new \Jaxon\Response\Response();
        $xResponse->alert($e->getMessage());
        
        $xResponseManager = new \Jaxon\Response\Manager();
        $xResponseManager->append($xResponse);
        $xResponseManager->send();
        exit();
    }
```

**Comment by feuzeu** [comment]
Ths issue is fixed. Your initial code should be working as expected.

**Comment by nevtag** [comment]
thank you, it's working fine.
