### ISSUE TITLE
register existing method in object

### ISSUE THREAD

**Issue by bzawislok** [jaxon-php/jaxon-core#124]
jaxon always want to call statically method in class 
but my object `user` was declared previously and have some important data stored as an class attribute, which it does not have when called statically

example code:

$user = new User();
$user->check_session_login();  //now $user->logged  change from false to true

$jaxon->register(Jaxon\Jaxon::CALLABLE_FUNCTION, 'jaxon_user_level_change',["class"=>User::class,"alias" => "user_level_change"]);

if($jaxon->canProcessRequest())
{
    $jaxon->processRequest();
}

in older version i use statement where i passed variable with object 
	$xajax->registerFunction(array('user_level_change',$rcp,'xajax_user_level_change'));

**Comment by feuzeu** [comment]
Hi,

Try this.
```php
$jaxon->di()->set(User::class, function() {
    $user = new User();
    $user->check_session_login(); //now $user->logged change from false to true
    return $user;
});

$jaxon->register(Jaxon\Jaxon::CALLABLE_FUNCTION, 'jaxon_user_level_change',["class"=>User::class,"alias" => "user_level_change"]);
```

When doing like that, the `User` object will be created only when it is needed.
Not when you call another exported function, for example.

**Comment by bzawislok** [comment]
I found another way, in the user_level_change function I used   
global $user;
$user->isLogged();

previous was:
$this->isLogged()

**Comment by feuzeu** [comment]
It is recommended not to use global variables.

https://stackoverflow.com/questions/5166087/php-global-in-functions
