### ISSUE TITLE
Type hint

### ISSUE THREAD

**Issue by esteban-turnocheck** [jaxon-php/jaxon-core#13]
Hi. I've just met jaxon, and seems very promising. However, i'm getting an error that makes me doubt if i should be using it.
The error is
Default value for parameters with a class type hint can only be NULL
And the line where it takes me is 
`    public function jQuery($sSelector = '', string $sContext = '')`
(that is jaxon-php/jaxon-core/src/Module/Controller.php on line 113)

But [here](http://php.net/manual/it/language.oop5.typehinting.php), it says "Type hints cannot be used with scalar types such as int or string". So, is this an error or i'm using it wrong? Can i safely remove the string hint? Is there many more around the code i should look for?
Thanks in advance!

**Comment by feuzeu** [comment]
The 2.0 branch is still under development and not ready for production. Many new features, including the Module and Controller, are not yet fully tested and documented.

**Comment by esteban-turnocheck** [comment]
Oh! Ok! I'm sorry to bother you, in that case. Should i be using branch 1.0, then?

**Comment by feuzeu** [comment]
Testing the 2.0 branch and reporting issues as you already did is very useful.
But if you want to use the library in a real world app, the 1.0 branch which is much more stable.

**Comment by esteban-turnocheck** [comment]
Ok. I'm just discovering jaxon and still a bit confused. I'll keep using and testing 2.0 branch until i go to production, so i'll keep reporting issues if/when they appear.
I've left another question / issue in the jaxon-codeigniter plugin, but that's another story. 
Thanks for replying and solving this one so quickly!

**Comment by feuzeu** [comment]
Fixed in the [v2.0-beta.14](https://github.com/jaxon-php/jaxon-core/releases/tag/v2.0-beta.14) release.
