### ISSUE TITLE
Error signaling from executed js

### ISSUE THREAD

**Issue by esteban-turnocheck** [jaxon-php/jaxon-core#14]
Hi!
When you use the script method of the response object to execute js code on the client, if the code fails, the behaviour might be unpredictable and, more dangerously, the client never finds out (as opposed to regular js code which shows in the console).
This is the eval function which runs the script

```
jaxon.js.execute = function(args) {
    args.fullName = 'execute Javascript';
    var returnValue = true;
    args.context = args.context ? args.context : {};
    args.context.jaxonDelegateCall = function() {
        	eval(args.data);
    };
    args.context.jaxonDelegateCall();
    return returnValue;
}

```

That eval function, in such a case, throws an exception. But 
```

        try {
            if (false == jaxon.executeCommand(obj)) 
                return false;
        } catch (
        }
```

Here, it is silently discarding it.
This...
```
        try {
            if (false == jaxon.executeCommand(obj)) 
                return false;
        } catch (e) {
        	alert(e);
        }

```

...would do. (or maybe console.log(e))
Of course, there might be better approaches (callbacks to some parameterized function o even to php?), but it would not hide potential errors in response->script() code.
If you patch your code about it, please let  me know to load the jaxon.core.js back from the cdn (now i'm using local copy with said patch)
Thanks!!

**Comment by feuzeu** [comment]
This issue was moved to jaxon-php/jaxon-js#3
