### ISSUE TITLE
File Upload doesn't work after updating to 4.8.0

### ISSUE THREAD

**Issue by Waxter81** [jaxon-php/jaxon-core#141]
I have just update jaxon-core from 4.7.1 to 4.8.0. Since then, i'm not able to work File Upload feature.

I register a Callable Function (with callable Class doesn't work either) like this:

```
$jaxon->register(Jaxon::CALLABLE_FUNCTION, 'saveFile', ['upload' => "'file-input'"]);

function saveFile() {           
    $response = jaxon()->newResponse();
    $response->alert('Hello World');
    return $response;
}

```

My Script is something like this:

`<input type="file" id="file-input" name="example_file" onchange="jaxon_saveFile()">`

On 4.7.1 everything works fine, the function is executed and we get Response and Hello World alert:

![image](https://github.com/user-attachments/assets/84e66afa-7eb0-4063-b3b9-168a572a423e)

Then, I update to 4.8.0 and with the same code, function is not executed, and we doesn't get response

![image](https://github.com/user-attachments/assets/a21f07e1-341a-41db-b8b6-e015d44820e8)

![image](https://github.com/user-attachments/assets/f90d1582-be7a-40bc-8436-56b589e18b14)

I have experienced this behavior both in local and in production environment.

**Comment by feuzeu** [comment]
Hi,

Please can you check if there is any message displayed in the console tab of the debug tool?

**Comment by Waxter81** [comment]
![image](https://github.com/user-attachments/assets/1f9bfe0e-de3f-4e6c-84ae-ac4e72c5b685)

**Comment by Waxter81** [comment]
There is no error message on console tab of the debug tool.

![image](https://github.com/user-attachments/assets/1e6ad76b-9954-41ab-bafe-c902db43cba8)

![image](https://github.com/user-attachments/assets/cc191994-f2a0-48f2-9eed-c7e2b05cf949)

![image](https://github.com/user-attachments/assets/02819d77-cc59-4d87-bb60-6d7e58ee7ed4)
![image](https://github.com/user-attachments/assets/c6fce479-dd09-4a67-8631-fc7090725ca6)
![image](https://github.com/user-attachments/assets/4f8823f4-1479-4dc1-9e68-da12e16d4f74)
![image](https://github.com/user-attachments/assets/fa7476fd-828e-41df-b871-3e39c8676052)
![image](https://github.com/user-attachments/assets/a4385e88-d15d-45d7-9a50-45805914d838)
![image](https://github.com/user-attachments/assets/9181b0b7-d2dc-4b68-8c82-a38c7886487c)
![image](https://github.com/user-attachments/assets/03df3224-bf9a-421f-975c-c5339fadf7a7)
![image](https://github.com/user-attachments/assets/784d940c-7f75-4a8d-bf8c-a6fa0681b795)
![image](https://github.com/user-attachments/assets/18b6e4b8-b9d3-41bf-92dc-b9da1fcec8c0)
![image](https://github.com/user-attachments/assets/aacb4faf-fd50-4b77-9cae-110ab96330d0)
![image](https://github.com/user-attachments/assets/b3e2eaed-a425-415d-a574-ec982a38f44b)

**Comment by feuzeu** [comment]
Hi,
The issue is fixed in the [4.8.8 release](https://github.com/jaxon-php/jaxon-core/releases/tag/v4.8.8) of this package, which loads the [version 4.0.8](https://github.com/jaxon-php/jaxon-js/releases/tag/v4.0.8) of the js library, where the issue is actually fixed.

**Comment by Waxter81** [comment]
Thank you!! 

I have update to 4.8.8 , but I have tested and for me it's not working yet....

In 4.7.1 (jaxon-js 3.3) I get Jaxon Response. In Payload I can see "Form Data":
![image](https://github.com/user-attachments/assets/56483186-ff77-4e12-99c2-f36563b7c5dd)

![image](https://github.com/user-attachments/assets/49354148-20e7-49a1-b606-8a442da79d80)



In 4.8.8 (jaxon-js 4.0.8) I don't get Jaxon Response (empty). There is no error in Debug Console. Request Payload shows like this:
![image](https://github.com/user-attachments/assets/4d8df6c7-435b-4b93-929f-d6a4ef393667)

![image](https://github.com/user-attachments/assets/e582eb53-ce08-4299-9faa-a2a830581a67)

**Comment by feuzeu** [comment]
Sorry, I just realized that I forgot to generate the distributed files. So the release doesn't include the fix.
I'll create a new release in a few minutes.

**Comment by Waxter81** [comment]
Tested and working.

Thank you!!
