### ISSUE TITLE
Question about migrating from xajax: synchronous call to javascript xajax.request()

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-core#16]
Hello,

First, I want to thank you that you have updated the project xajax and you have adapted and improved.

I am updating an old project that uses xajax for form validation.

I use this function, which calls a function registered in xajax with the name xajax_FormName.

```
function formValidate(frmName)
{
	frm=document.forms[frmName];

	var isValid=xajax.request({xjxfun:"xajax_"+frmName},{parameters:[xajax.getFormValues(frm.name,true)],mode:'synchronous'});

	if(isValid)
		frm.submit();

	return isValid;
}
```

What is the equivalent jaxon call for this line?

```
	var isValid=xajax.request({xjxfun:"xajax_"+frmName},{parameters:[xajax.getFormValues(frm.name,true)],mode:'synchronous'});
```

Thanks, I have not found any similar example in the documentation

**Comment by feuzeu** [comment]
Hello,

You need to declare your function as synchronous when you register it, as in the following example: https://github.com/jaxon-php/jaxon-examples/blob/master/hello.php.
Then you call it as usual. You will see in the generated javascript function that the 'mode' option is set to 'synchronous'. Check for example the source code of this page: https://www.jaxon-php.org/exp/hello.php.

**Comment by jatubio** [comment]
Thank you for your fast reply.

I have changed xjxfun to jxnfun and now the function is called, but the json response it's not reaching the browser. I checked it with Developer Tools and all i get is: 'This request has no response data available'.

My project was developed using Ajax 5, and was working before update to Jaxon. I'm debugging and watching Response returned object and it's correct. I don't know where the returned object it's not reaching the browser.

**Comment by jatubio** [comment]
I have found the problem, but don't know how to solve: #18

**Comment by feuzeu** [comment]
Regarding the initial question, I recommend always using the names generated by Jaxon to call the exported PHP classes and functions.
The implementation may change without prior notice, and the Jaxon Request Factory provides methods to easily generate calls from PHP .
