### ISSUE TITLE
Question about get debug messages on a browser window

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-core#17]
Hello,

When i set `$jaxon->setOption('core.debug.on', true);` some times I get the messages on a new browser window, but another times, I get the Messages sequentially as alerts box.

I do not know why this happens. Is there any way to always force the browser window for debugging messages?

Thank you

**Comment by feuzeu** [comment]
I've never met this issue.
Does it happen at random?

**Comment by jatubio** [comment]
In my web app debug messages show in browser window. But, in your example: HelloWorld, they show in alerts boxes.

**Comment by feuzeu** [comment]
This issue was moved to jaxon-php/jaxon-js#5
