### ISSUE TITLE
Why getFormValues don't return unchecked checkboxes?

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-core#19]
When I want to validate if a checkbox has been marked on a form, it is impossible for me because getFormValues does not return that unchecked checkboxes and my code only validates the fields that come from that function.

I know how to fix it because I already had to modify that part of the javascript code in xajax. But, apart from not be recommendable for possible changes in future updates, I'm curious to know why those fields are not returned?

Thanks

**Comment by feuzeu** [comment]
Hi,
Unchecked checkboxes are not included in form values in order to conform to the HTML standard.
https://www.w3.org/TR/html401/interact/forms.html#h-17.13.2.
You'd rather handle that in your PHP application, since you will have the same behavior when processing any standard POST query.
Regards

**Comment by jatubio** [comment]
Thanks for the clarification
