### ISSUE TITLE
Google Chrome warning: [Deprecation] Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-core#20]
I'm getting this message in Google Chrome, on Developers Tools Log:

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

On: jaxon.core.min.js:1

**Comment by feuzeu** [comment]
This issue was moved to jaxon-php/jaxon-js#4
