### ISSUE TITLE
Fuelphp

### ISSUE THREAD

**Issue by stvowi** [jaxon-php/jaxon-core#22]
How about it to make  a axon library integration (package) for the Fuelphp 1.8/ 1.9 dev [framework](https://fuelphp.com/) ?

**Comment by feuzeu** [comment]
Hi,
There is no plan for a integration package for Fuelphp in our current milestone.
May be we could add it in the next one, but it will not be released before 6 to 8 weeks.

Meanwhile, you can use the Armada package (https://github.com/jaxon-php/jaxon-armada) which provides features that are nearly the same as in the integration packages.
For instance, you will be able to reuse the same Jaxon classes when migrating to the integration package.

**Comment by stvowi** [comment]
Thanks for the answer.

**Comment by feuzeu** [comment]
You're welcome, @stvowi.
I am available to provide some help, in the case you want to create the plugin by youself.
