### ISSUE TITLE
response->append clears form values when dinamically adding more form elements

### ISSUE THREAD

**Issue by seba1rx** [jaxon-php/jaxon-core#25]
In my Smarty + Jaxon app I have the following issue:
(not using jaxon-smarty)

jaxon.php = Jaxon 2.0-beta.25
jaxon.core.js = jaxon.core.js 327 2007-02-28 16:55:26Z

When I want to append a new row of form elements to my form, all previous form values get cleared,

this is my demo code:

$jxnr = new Jaxon\Response\Response();
$template = $smarty->fetch('file:[sub]newFormRow.html');
$jxnr->append("formBox","innerHTML",$template);

If I create a string with all the template html code and then I append it to the element using jquery, it works:

//$jxnr->append("formBox","innerHTML",$template);
$jxnr->script("  $('#formBox').append( '".$str_template."' );  ");

Can this be a jaxon issue?

**Comment by feuzeu** [comment]
A call to `$jxnr->append("formBox","innerHTML",$template);` execute the following js code in the browser: `jaxon.$('formBox').innerHTML += '<html code>'`.

Try this code to see if the error still occurs.
`$jxnr->script("jaxon.$('formBox').innerHTML += '".$str_template."';");`

**Comment by feuzeu** [comment]
I would like to suggest that you upgrade both your PHP and Js libraries to the latest versions. Many stable versions were released since the one you are using.
I also suggest the use of the jQuery response plugin, so you can write this code instead.
`$jxnr->jq('#formBox')->append($str_template);`
It is more concise and readable.

**Comment by seba1rx** [comment]
I will do the upgrade and use the jqurery plugin,  but for now, I checked the script:

// appending but still clearing previous form fields
$jxnr->script("jaxon.$('formBox').innerHTML += '".$str_template."';");  

// still using jquery workarround until I try lquery plugin
$jxnr->script(" $('#formBox').append( '".$str_template."' ); ");

**Comment by feuzeu** [comment]
It's a bug in the js function.
The `innerHTML` attribute does not include the form values, since there are not part of the DOM. They have to be copied explicitly.
Please enter an issue on the `jaxon-php/jaxon-js` package.

**Comment by feuzeu** [comment]
This issue was moved to jaxon-php/jaxon-js#7

**Comment by feuzeu** [comment]
Hi,
I've reimplemented the DOM append() and prepend() functions using [insertAdjacentHTML()](https://developer.mozilla.org/fr/docs/Web/API/Element/insertAdjacentHTML).
So this issue is fixed for browsers that have this function available.
