### ISSUE TITLE
Hello I need help with the installation

### ISSUE THREAD

**Issue by feuzeu** [jaxon-php/jaxon-core#29]
_From @bioraft-xx on April 18, 2018 14:28_

Hello, I am a newbe with this and I need help, I installed Composer in my server and my developement macchine, I am using Apache 2.4 with PHP 7.2.4. Ok with composer installed in both my server and my machine I installed Jaxon.

but when I try to execute even the simple example I got this error:

Fatal error: Uncaught Error: Call to undefined function jaxon() in C:\Webprojects\Web_Authority_Framework\WebApp\test3.php:19 Stack trace: #0 {main} thrown in C:\Webprojects\Web_Authority_Framework\WebApp\test3.php on line 19

is the line $jaxon=jaxon();

I don't know what more I can do... I think I am missing somethin and I have the same error in my server and my development machine. I am migrating some code from Xajax and I need to migrate to PHP 7 and I think with Jaxon will be the way.

Please help and thanks.

_Copied from original issue: jaxon-php/jaxon-js#11_

**Comment by bioraft-xx** [comment]
Hello thanks for your answer, yeah I was reading about the autoload, but where is that file, when I put that line of code, anyway it looks for that file, where can I find that file? should I have to download the jaxon-core files too, or is it enough with the files that install composer when you install Jaxon? sorry I am really lost about this and I just have to know how to use the autoupload...

**Comment by VFiber** [comment]
I think you have to know composer first, and you will be able to answer your question yourself.
Composer is a dependency management software and it comes with an autoloader, what "loads your classes automagically".

By default, using composer require / install creates a vendor folder and a composer.json, downloads the required package into "vendor/package-name" and creates an autoloader in vendor/autoload.php. If you include that autoloader, every new Classname() call is gonna call the autoloader, if the given class not exists and loads from the vendor/* folder (99% of the packages are supporting autoloader).

https://getcomposer.org/doc/01-basic-usage.md#autoloading

Even you can use autoloader, if you follow PSR-4 rules of putting your namespaces / classes under a same folder structure.
Please note, this is a very dummy explanation, please read after Autoloader, PSR-4 and Composer to understand the concepts.

**Comment by bioraft-xx** [comment]
Thanks for the information, well I didn't know that you have to choose the directory where you want to install Jaxon, and well right now I selected the right path (or the path where I wanted to install Jaxon) and I could select the autoload.php with no problems, and right now the script works perfect.

Thanks a lot right now reading the Jaxon documentation and getting into this, to migrate my code from xajax to jaxon for php 7 support.

Well it looks like a simple thing but thanks hopefully this will help to newbies like me...

Thanks a lot people...
