### ISSUE TITLE
Hello with old commands from xajax to jaxon

### ISSUE THREAD

**Issue by bioraft-xx** [jaxon-php/jaxon-core#30]
Hello, I am migrating from xajax to jaxon and until now everything is fine, but something appear. In the past I used this command:

xajax.callback.global.onRequest = javascriptfunction1; 
xajax.callback.global.onComplete = javascriptfunction2;

is there options for this in jaxon? Well I am thinking about this

$jaxon->register(Jaxon::PROCESSING_EVENT, Jaxon::PROCESSING_EVENT_BEFORE, 'functionName');
$jaxon->register(Jaxon::PROCESSING_EVENT, Jaxon::PROCESSING_EVENT_AFTER, 'functionName');

Thanks for the info...

**Comment by feuzeu** [comment]
Hi,
The function you register with the `$jaxon->register()` methods are PHP functions that execute on your server, resp. before and after processing the request.
What you should write now is
```javascript
jaxon.callback.onRequest = javascriptfunction1;
jaxon.callback.onComplete = javascriptfunction2;
```

**Comment by walmartshopper** [comment]
The code above no longer works in version 4.  jaxon.callback does not exist in v4, but there was no mention of this in the "Migrating from version 3" documentation.  Can it be added back in v4?

I was using it to show and hide a small loading box during request processing:
```
jaxon.callback.onRequest = function() {
    $('#loading').show()
}
jaxon.callback.beforeResponseProcessing = function() {
    $('#loading').hide()
}
```

**Comment by walmartshopper** [comment]
Figured out how to do it with version 4:

```
jaxon.ajax.callback.callback.onRequest = function() { $('#loading').show(); }
jaxon.ajax.callback.callback.beforeResponseProcessing = function() { $('#loading').hide(); }
```

**Comment by feuzeu** [comment]
Hi,

The js callbacks are documented here: https://www.jaxon-php.org/docs/v4x/requests/js-callbacks.html.

In your case, you first need to add your callbacks in your js code.
```js
my.app.callbacks = {
    onRequest: function() { $('#loading').show(); },
    beforeResponseProcessing: function() { $('#loading').hide(); }
}
```

And then attach them to your PHP directories or classes when they are registered.

In the following example, the callbacks are attached to all the classes in a registered directory.
```php
jaxon->register(Jaxon::CALLABLE_DIR, '/the/class/dir', [
    'namespace' => 'Ns',
    'classes' => [
        '*' => [
            'callback' => "my.app.callbacks"
        ],
    ],
]);
```

**Comment by walmartshopper** [comment]
Thanks, it just seems a little over-complicated for what I want to do.  Basically I just wanted global JS callbacks that run some client-side code for any jaxon call.  The code i posted above does exactly what I need, so I'm happy with it.  All I had to do was change "jaxon.callback" to "jaxon.ajax.callback.callback" and it seems to work the same way it did in v3.

**Comment by feuzeu** [comment]
First of all, it's never a good idea to use internal undocumented feature of any library, since it may change without further notice.

And, sincerely, "over-complicated"? Seriously. I am just a step away from advising you to use another library.

**Comment by walmartshopper** [comment]
> First of all, it's never a good idea to use internal undocumented feature of any library, since it may change without further notice.

Sorry, didn't mean any offense.  But to be fair, the solution you gave in the original answer years ago was also an undocumented feature, so I didn't think it was a big deal to ask about an equivalent for v4.
