### ISSUE TITLE
TypeError with new Version 2.2.0

### ISSUE THREAD

**Issue by ITspirit** [jaxon-php/jaxon-core#32]
After upgrading to new Version (2.2.0) i get these errors:

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ReflectionClass::newInstanceArgs() must be of the type array, null given in /var/www/vendor/jaxon-php/jaxon-core/src/Request/Support/CallableObject.php:134

Stack trace:
#0 /var/www/vendor/jaxon-php/jaxon-core/src/Request/Support/CallableObject.php(134): ReflectionClass->newInstanceArgs(NULL)
#1 /var/www/vendor/jaxon-php/jaxon-core/src/Request/Support/CallableObject.php(158): Jaxon\Request\Support\CallableObject->setCallable()
#2 /var/www/vendor/jaxon-php/jaxon-core/src/Request/Support/CallableObject.php(374): Jaxon\Request\Support\CallableObject->getRegisteredObject()
#3 /var/www/vendor/jaxon-php/jaxon-core/src/Request/Plugin/CallableObject.php(272): Jaxon\Request\Support\CallableObject->call('changeVariation...', Array)
#4 /var/www/vendor/jaxon-php/jaxon-core/src/Plugin/Manager.php(355): Jaxon\Request\Plugin\CallableObject->processRequest()
#5 /var/www/ in /var/www/vendor/jaxon-php/jaxon-core/src/Request/Support/CallableObject.php on line 134

I made a downgrade to 2.1.5 and the Error disappeared.

Occurs on PHP 7.2.7

**Comment by feuzeu** [comment]
Fixed in release 2.2.1.
