### ISSUE TITLE
Please use jQuery() instead of $() to prevent conflicts with other Javascript frameworks

### ISSUE THREAD

**Issue by plampix** [jaxon-php/jaxon-core#37]
Hi,

We're looking into upgrading to jaxon-core (we still use the old xajax stuff), and still use some legacy libraries. That's why $() is not an alias for jQuery() in our case. Could you please use jQuery() instead of $() in JQuery/Dom/Element.php?

**Comment by feuzeu** [comment]
Hi,
Please check out the latest https://github.com/jaxon-php/jaxon-core/tree/v2.2.4 release.
Set the `core.jquery.no_conflict` oprion to true, and jQuery() will be used  instead of $().
