### ISSUE TITLE
Question on registering a function to receive form data and files

### ISSUE THREAD

**Issue by seba1rx** [jaxon-php/jaxon-core#40]
Hello There I have a question regarding registering a function that receives form data and files.

Looking at the example code, how must be a function registered in order to be able to receive form data and also files?

I cannot change the structure of the app, and the upload documentation won't give me any hint on how to do this given the app structure.

I tried several tests but failed...

(The example code has been reduced to the important stucture of the web app in order to give context to the question)

The example Jaxon controller

```
	require_once ($_SERVER['DOCUMENT_ROOT']. '/vendor/autoload.php');
	require_once ($_SERVER['DOCUMENT_ROOT']. '/myIncludedFiles.php');
	
	use Jaxon\Jaxon;
	use Jaxon\Response\Response;
	$jaxon = jaxon();

	$jaxon->setOption('js.lib.uri', '/src');
	$jaxon->setOption('js.app.minify', true);
       
	$jaxon->register(Jaxon\Jaxon::USER_FUNCTION, 'myFunction');
	## How would it be in order to register a function that receives form data and files?


	$jaxon->processRequest(); 

	function myFunction( $formData ){
		$jxnr = new Jaxon\Response\Response();
		$jxnr->setReturnValue($formData );		
		$jxnr->script(" console.log('debugging in browser console...') ");
		return $jxnr;
	}

	$smarty->assign('jxn_js', $jaxon->getJs());
	$smarty->assign('jxn_getScript', $jaxon->getScript() );
	$smarty->assign('jxn_getCss', $jaxon->getCss());
```

The example html

```
<form id="myForm" name="myForm">
	<input id="someText" name="someText" type="text">    
	<input type="file" id="upload_example" name="example_file" />
</form>

<script>
	jaxon_myFunction(jaxon.getFormValues('myForm'));
</script>
```

**Comment by feuzeu** [comment]
Hi,
Try this
```php
$jaxon->register(Jaxon::USER_FUNCTION, 'myFunction', ['upload' => "'upload_example'"]);
```
That's how options are passed to functions when they are registrered.

**Comment by seba1rx** [comment]
I had some progress now thanks to your advice, now I am saving the image but lost all other form data.

I get `PHP Notice:  Undefined index` because there is no form data.
I debugged the content and nothing is being received as agrs in the function.

```
$jaxon->setOption('upload.default.dir',$_SERVER['DOCUMENT_ROOT'].'/upl/temp');
$jaxon->register(Jaxon\Jaxon::USER_FUNCTION, 'myFunction', ['upload' => "'upload_example'"]);
```
I decided to go arroud this and created a simple ajax function that creates a formData var and adds the image to it, then it POSTs it to myUploaderController.php and waits for the response, if ok, then it calls 

`jaxon_myFunction(jaxon.getFormValues('myForm'));`


Here is my workarroud:

html calling ajax function:
`<button type="button"  onclick="processImage();">Save all this data</button>`

Jaxon controller:
```
$jaxon->register(Jaxon\Jaxon::USER_FUNCTION, 'prepareForm');
$jaxon->register(Jaxon\Jaxon::USER_FUNCTION, 'myFunction');
$jaxon->processRequest(); 

function prepareForm(){
	$jxnr = new Jaxon\Response\Response();
	
	// setup form html with smarty in my case
	
	$jxnr->setFunction('processImage', '', "
		var fileInput = document.getElementById('upload_example');
		var file = fileInput.files[0];
		var formData = new FormData();
		formData.append('file', file);
		
		//##DEBUG:
		//for (var [key, value] of formData.entries()) { 
		//	console.log('log: ' + key, value);
		//}
		
		//2097152 = 2MB
		
		if(formData.get('file')['size'] > 2097152 ){
			console.log('too big')
		}else{
			$.ajax({
				url: 'util/myUploaderController.php',
				type: 'POST',
				data:  formData,
				contentType: false,
				cache: false,
				processData: false,
				dataType: 'json'
			}).done(function (response) {
				if(response.hasError){
					//ok, call jaxon
					jaxon_myFunction(jaxon.getFormValues('myForm'));
				}else{
					//ERROR, popMsg
					console.log('ERROR: '+response.msg)
				}
				//console.log('bo: '+response.bo);
				//console.log('msg: '+response.msg);
			});
		}
		
		return false;
	");
	
	return $jxnr;
}

function myFunction( $formData ){
	$jxnr = new Jaxon\Response\Response();
	$jxnr->setReturnValue($formData );		
	$jxnr->script(" console.log('debugging in browser console...') ");
	
	//validate form data and do whatever I need to do with it
	
	return $jxnr;
}
```

My uploader controller demo:
```
<?php

// deal with image here

$response = array(
	'hasError' => true,
	'msg' => 'demo msg',
	'data' => null
);

echo json_encode($response);
?>
```

**Comment by feuzeu** [comment]
Hi,
Does your browser support FormData?
When the browser does not support FormData, Jaxon will send 2 requests to your application. The first request uploads the files, and thus contains no data other than the files. The second request will then contain your form data.
Replace `$jaxon->canProcessRequest();` with the following to handle this case
```php
if($jaxon->canProcessRequest())
{
    // Process the request.
    $jaxon->processRequest();
}
else if($jaxon->hasUploadedFiles())
{
    // Process upload.
    $jaxon->saveUploadedFiles();
}
```

**Comment by seba1rx** [comment]
Hello, thanks for your reply!

I tried

```
if($jaxon->canProcessRequest()){
	// Process the request.
	$jaxon->processRequest();
}else if($jaxon->hasUploadedFiles()){
	// Process upload.
	$jaxon->processRequest();
	$jaxon->saveUploadedFiles();
}
```

and also

```
if($jaxon->canProcessRequest()){
	// Process the request.
	$jaxon->processRequest();
}else if($jaxon->hasUploadedFiles()){
	// Process upload.
	$jaxon->processRequest();
	$jaxon->saveUploadedFiles();
}
```

I get the image in my configured directory, but still myFunction wont get the args.

**Comment by feuzeu** [comment]
Run the request in debug mode and see what's the value returned by the `jaxon.getFormValues('myForm')` call.

Also try to put the file input field in a separated form.
```html
<form id="myForm" name="myForm">
	<input id="someText" name="someText" type="text">    
</form>

<form>
	<input type="file" id="upload_example" name="example_file" />
</form>
```

**Comment by feuzeu** [comment]
Hi,

I have made a change to properly decode parameters when they are "multipart/formdata" encoded.
Check out the 2.2.6 release.

There've also been some changes in the js library: Raw values of input fields of type file are no more included form data, and "multipart/formdata" encoding is used if the user actually selects files to upload.
They are in the 2.0.6 release.

**Comment by seba1rx** [comment]
Wow thanks!

I'll check it out!
