### ISSUE TITLE
Version 3.x

### ISSUE THREAD

**Issue by feuzeu** [jaxon-php/jaxon-core#43]
Hi all,

I've started working on the 3.x version of the Jaxon library, and there's already  a few beta releases. It's still an ongoing work, and I would like to share the main features that are expected in the next releases.

All comments and suggestions are welcome.

1. **Lightweight class registration**

Until now, registering a user callable object with jaxon actually means creating an instance of both the class and the `CallableObject`, which is the wrapper class Jaxon internally uses to generate Javascript code and handle Ajax requests.
```php
$jaxon->register(Jaxon::CALLABLE_OBJECT, new FirstClass());
$jaxon->register(Jaxon::CALLABLE_OBJECT, new SecondClass());
$jaxon->register(Jaxon::CALLABLE_OBJECT, new ThirdClass());
```
When using the `jaxon-armada` or any framework integration package, we had to avoid registering the classes when processing a request, since only the requested class actually needs to be instanciated.
```php
if($armada->canProcessRequest())
{
    // Process the request
    $armada->processRequest();
}
else
{
    // Register all the classes. Then they are all instanciated.
    $armada->register();
}
```

In the 3.x version, the user registers classes instead of objects, and Jaxon will instanciate them when needed.
```php
$jaxon->register(Jaxon::CALLABLE_CLASS, 'FirstClass');
$jaxon->register(Jaxon::CALLABLE_CLASS, 'SecondClass');
$jaxon->register(Jaxon::CALLABLE_CLASS, 'ThirdClass');
```

Directories will also be registered the same way, with no object created until it is actually needed.
```php
$jaxon->register(Jaxon::CALLABLE_DIR, '/path/to/the/first/dir/');
// With namespace
$jaxon->register(Jaxon::CALLABLE_DIR, '/path/to/the/second/dir/', ['namespace' => 'Ns\Jaxon\Second']);
```

The same will apply to `jaxon-armada` or any framework integration package.
```php
// Register the classes. No object is created.
$armada->register();
if($armada->canProcessRequest())
{
    // Process the request. Only the requested object is created.
    $armada->processRequest();
}
```

2. **Dependency injection**

This feature is already implemented in the latest release https://www.jaxon-php.org/docs/advanced/dependency-injection.html.

The next releases will take the feature a step further by allowing the use of third party dependencies. For example when using the Laravel framework, the user will be able to inject Laravel dependencies in Jaxon classes with no extra cost.

3. **Config based registration**

This feature will let the user specify the functions, classes and namespaces to register in a config file, instead on manually listing them in the code.
Until now, only the `jaxon-sentry` -based packages could benefit from this feature.

4. **Packages**

This may be the most important feature planned in the next releases, and also the most hard to implement.

A Jaxon package bundles a set of classes and templates, and implements all the features needed to provide a service, including the required user interfaces.
After installing a Composer package, setting some config options and adding a couple of lines in a template, the user will be able to gain access to a service from a new or an existing application.

**I need your comments**

Please let me know if there's any feature you would like to see in the next releases, if you foresee any issue with the planned features, or if you have any questions.

Thank you.

**Comment by seba1rx** [comment]
Hello, great to hear this news.

I truly appreciate all your efforts to take Jaxon into the next level.

I came here to make a comment on something that just gave me some hard time to find out the problem and I found this news...

Well, when registering a function if there is a whitespace at the end of the string that corresponds to the name of the function, lets say:

`$jaxon->register(Jaxon\Jaxon::USER_FUNCTION, 'myFunction '); //whitespace at the end of name
`

It will return an HTML content and not the jaxon object.

I haven't checked if there is a trim function in later releases of the release I am using, but still, I wanted to point this out since this is one of those cases in which you wouldn't pay attention 
to the section of code where you register your functions.

And that's it, keep up the good work!

**Comment by feuzeu** [comment]
Hi All,

Good news! The version 3 is almost ready.
I'm currently updating the docs, and right after that I'll release a stable version.

All the changes listed above have been implemented, excepted the package management which I'll add in the next releases.

Thanks!

**Comment by feuzeu** [comment]
Hi all,
Just tagged the [3.0 beta 7 release](https://github.com/jaxon-php/jaxon-core/releases/tag/v3.0-beta.7), which is probably the last beta release before the final version.
Still updating the docs.

**Comment by feuzeu** [comment]
Finally done!

I'm very excited to announce the stable release of the version 3.

Here's an overview of the main changes: https://www.jaxon-php.org/docs/v3x/about/changes.html

I hope you'll enjoy using it.
