### ISSUE TITLE
Question: callback.global

### ISSUE THREAD

**Issue by nevtag** [jaxon-php/jaxon-core#5]
Hi Thierry,

I use xajax callback funktions in javascript.

```
<script type="text/javascript">
//<![CDATA[
  xajax.callback.global.onRequest = function() { $('#loading').css('display','block'); }
  xajax.callback.global.beforeResponseProcessing = function() { $('#loading').css('display','none'); }
//]]>
</script>
```

Have you an equivalent in jaxon?
I saw that you have callbacks pre-processing and post-processing, but that are on server.

Regards,
Joc

**Comment by feuzeu** [comment]
Hi Joc,

There've been no change in the javascript functions.
You just have to replace xajax with jaxon, and it should be working the same way as before.

PS: If you are using jQuery, you may want to checkout the jaxon-jquery package https://github.com/jaxon-php/jaxon-jquery. It provides a jQuery-like API to modify the webpage content and presentation with PHP.

Regards,
Thierry

**Comment by feuzeu** [comment]
Any feedback on this issue?

**Comment by nevtag** [comment]
Sorry, the github mail system did not working well, I got only the close mail.
I will try it.

**Comment by nevtag** [comment]
> You just have to replace xajax with jaxon, and it should be working the same way as before.
That was what I try first, but it didn't work, so I make the issue.
But now it is working.
