### ISSUE TITLE
SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by Bytenex** [jaxon-php/jaxon-core#6]
Hi,

I get an error even when returning a newly created empty response.

POST Response:
`SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data`
Firefox Devconsole (JS error):
`SytaxError: expected expression, got '<'`

I can see the JSON array (when sending data e.g. innerHTML) but it breaks afterwards.

Specs:
Apache: 2.4
PHP: 7.0

**Comment by feuzeu** [comment]
What happens if you trim the newlines from the HTML code you are assigning?

**Comment by feuzeu** [comment]
Any feeback on this issue?

**Comment by Bytenex** [comment]
I'm sorry for this issue. Was my personal fault. My Response included some HTML header an therefore was invalid. Nothing wrong with Jaxon.
