### ISSUE TITLE
JAXON - SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by lxaraujo** [jaxon-php/jaxon-core#65]
Hello. I am trying to use Jaxon instead Xajax because I am migrating to PHP 7+ but I am facing a very strange issue.
Everything seems to be right, the jquery is being injected correctly inside the page and my class or function are also being registered.
The problem is when I generate the event that will trigger my function and create the $response.
As soon as $response = new Response() is executed a syntax error from json (jaxon.core.min.js:1) are reported.
the exact point where the error is reported is right at T+ in this part of the json string.
responseTex**t+**")")}catch(e){throw e}
I am here asking for a help to find an answer for this strange issue.
thank you very much.

**Comment by feuzeu** [comment]
Hi,
I think this error means that the Jaxon javascript library is unable to parse the response your app sent back.
This often happens when the app outputs additional debug data that is added to the Jaxon response.

Try to use the dev tools of your browser to see the response your app sends back.

**Comment by lxaraujo** [comment]
thank's for your response, but unfortunately the only thing that it shows is the syntax error message. I guessed that was my xdbug that was causing this but I tested in other browser and same thing came up. I am getting frustrated because Xajax is very simple to use and I am trying Jaxon for the same reason but this issue is driving me crazy. I am resourceless. I think the Jaxon website should have more complete examples about how to use this library, not only fragments of code, it seems a very good library. I learned Xajax almost only by  examples. If they can provide a complete file whit HTML and PHP from the beginning would be a great help. I will keep diging. thanks again for your attention.

**Comment by feuzeu** [comment]
Hi,
If the issue comes from your app as I guessed, using a different browser will not change anything.

If you are using Chrome or Firefox on Linux or Windows, press `Ctrl-Maj-i` to show the dev tools window, then go to the `Network` tab. You'll see your HTTP requests there. If the tab is empty, reload the page or make a new Jaxon request.

Click on a Jaxon request in the list, and all its details will appear in multiple tabs. The `Response` tab will show you the raw response sent by your application.
If this response is not json formatted, then it's the cause of your issue.

**Comment by feuzeu** [comment]
Concerning the examples, look at the repo at https://github.com/jaxon-php/jaxon-examples.
These are not "only fragments of code". They are full working examples you can install and run on your own server.
Only by following the simple instructions in the readme, you'll be able to run all the examples excepted those related to frameworks.

**Comment by lxaraujo** [comment]
It is returning a bad formed Json string with a syntax error message.
What bothers me is that I can even create the $response variable because
when it executes $response = new Response the error happens.
I don´t have an application really, I have a function or class (I have 2
different files to test) and only 1 event that is the onclick, with no
parameter only the called function.
The action that it was supposed to return is an alert(), but the processing
never reached that action because it dies when I try to create the
$response variable.
regarding the examples, when I go to
https://github.com/Jaxon/Jaxon/blob/master/examples/helloworld.php it
returns a 404 page not found.
I have just one php file with a very simple code. But don´t worry, I wil
keep my journey diging.
As we say here in my country (Brasil) I am a brazilian, I never quit.
rsrsrsrs

Em qui., 16 de jan. de 2020 às 09:25, Thierry Feuzeu <
notifications@github.com> escreveu:

**Comment by feuzeu** [comment]
Hi,
The link is https://github.com/Xajax/Xahax/blob/master/examples/helloworld.php
Make you include the composer autoload file in your own file. It may exmplain why you cannot create a `Response` object.

**Comment by lxaraujo** [comment]
Hello,

The Xajax example doesn´t help, I am using it since 2008 and I am very happy with it so I know how to use it.
The composer autoload file is already being loaded because it seems that Jaxon is working. It is creating and injecting the JavaScript parts. I can see inside my file on the debuger that JavaScript is being built and the call to my PHP function from the onclick event is there. The error happen exactly after I click the button. When Jaxon goes to my PHP function and reach $response = new Response the Json that is returned came with the sintax error. The example I need from Jaxon is the kind is shown for Xajax. step by step in the same file, very simple.

**Comment by lxaraujo** [comment]
This is my code:
<?PHP
require_once '../vendor/autoload.php';

use Jaxon\Jaxon;
use Jaxon\Response\Response;

$jaxon = jaxon();

$jaxon->register(Jaxon::CALLABLE_FUNCTION, "show");


 function show()
    {
        $response = new Response();
        $response->assign('div_tab', 'innerHTML', 'texto');
        return $response;
    }

?>
<!DOCTYPE html>
<html>
<head>
<meta content="charset=utf-8" />
<title>Title</title>
</head>
<body style="background-color:#81BEF7 ;">
<form>
<table border="1" align="left" bgcolor="#FFCC33" style="border-collapse:collapse">
	<tr>
    	<td align="right">&nbsp;<input type="button" value="Say Hello" onclick="<?php echo rq()->call('show') ?>" /></td>
    </tr>
  </table>
  <div id="div_tab"></div>
</form>
<?PHP
    echo $jaxon->getScript(true,true);
?>
</body>
</html>
<?PHP
    if ($jaxon->canProcessRequest()) {
        $jaxon->processRequest();
    }
?>

**Comment by lxaraujo** [comment]
this is my code. Can you help seeing it?

<?PHP
require_once '../vendor/autoload.php';

use Jaxon\Jaxon;
use Jaxon\Response\Response;

$jaxon = jaxon();

$jaxon->register(Jaxon::CALLABLE_FUNCTION, "show");


 function show()
    {
        $response = new Response();
        $response->assign('div_tab', 'innerHTML', 'texto');
        return $response;
    }

?>
<!DOCTYPE html>
<html>
<head>
<meta content="charset=utf-8" />
<title>Title</title>
</head>
<body style="background-color:#81BEF7 ;">
<form>
<table border="1" align="left" bgcolor="#FFCC33"
style="border-collapse:collapse">
   <tr>
       <td align="right">&nbsp;<input type="button" value="Say Hello"
onclick="<?php echo rq()->call('show') ?>" /></td>
    </tr>
  </table>
  <div id="div_tab"></div>
</form>
<?PHP
    echo $jaxon->getScript(true,true);
?>
</body>
</html>
<?PHP
    if ($jaxon->canProcessRequest()) {
        $jaxon->processRequest();
    }
?>


Em sex., 17 de jan. de 2020 às 09:41, Thierry Feuzeu <
notifications@github.com> escreveu:

**Comment by feuzeu** [comment]
Hi,
Your issue is not due to debug output as I guessed, but to HTML output.
```php
<?PHP
    if ($jaxon->canProcessRequest()) {
        $jaxon->processRequest();
    }
?>
```
Since you have put the above code after the HTML code, the response to the Jaxon request will always contain the HTML code and the json data.

Try this
```php
<?PHP
require_once '../vendor/autoload.php';

use Jaxon\Jaxon;
use Jaxon\Response\Response;

$jaxon = jaxon();

$jaxon->register(Jaxon::CALLABLE_FUNCTION, "show");


function show()
{
    $response = new Response();
    $response->assign('div_tab', 'innerHTML', 'texto');
    return $response;
}

if ($jaxon->canProcessRequest()) {
    $jaxon->processRequest();
}
?>
<!DOCTYPE html>
<html>
<head>
<meta content="charset=utf-8" />
<title>Title</title>
</head>
<body style="background-color:#81BEF7 ;">
<form>
<table border="1" align="left" bgcolor="#FFCC33"
style="border-collapse:collapse">
   <tr>
       <td align="right">&nbsp;<input type="button" value="Say Hello"
onclick="<?php echo rq()->call('show') ?>" /></td>
    </tr>
  </table>
  <div id="div_tab"></div>
</form>
<?PHP
    echo $jaxon->getScript(true,true);
?>
</body>
</html>
```

**Comment by lxaraujo** [comment]
Good morning.

You are the best. Now it works very fine. Thank you very much for your help.
Now that I know, thank´s to you, the sequence of the expressions I will
begin to convert my files from Xajax to Jaxon and now I can jump to PHP 7.

Thank´s again.

Em sáb., 18 de jan. de 2020 às 13:05, Thierry Feuzeu <
notifications@github.com> escreveu:

**Comment by feuzeu** [comment]
You're welcome.
Happy coding with Jaxon!
