### ISSUE TITLE
Before processing the request bug?

### ISSUE THREAD

**Issue by safrick** [jaxon-php/jaxon-core#68]
Hello,

Thank You for updating Xajax!

I'm using Jaxon throughout the website and it's working fine everywhere. I needed help with this callback, either it's not working right or I'm misunderstanding something. The code below is located in the same file where all of the PHP functions are registered with Jaxon.

```
use Jaxon\Jaxon;
use Jaxon\Response\Response;
$jaxon = jaxon();

require_once $_SERVER['DOCUMENT_ROOT'] . '/configs/ajax_setup.php';

$jaxon->callback()->before(function($target, &$bEndRequest) {
	// Some business logic (user's session expired or app is offline)
	if (! business_logic){
		$objResponse = new Response();
		$objResponse->alert("We're offline now.");
		$bEndRequest = true;
		return $objResponse;
	}
});

other functions registered here

if($jaxon->canProcessRequest())
{
    $jaxon->processRequest();
}
```

**The docs state:**
The boolean parameter $bEndRequest is passed by reference. Its initial value is false, and if it is assigned the value true in the callback, the request processing is stopped, **and the returned response is sent back to the browser**.

**But the Debug Output Shows:**
RECEIVED [status: 200, size: 13 bytes, time: 84ms]:
{"jxnobj":[]}

Shouldn't the JavaScript response be returned or am I doing something wrong?

Using: "jaxon-php/jaxon-core": "~3.2" in vanilla PHP project.

**Comment by feuzeu** [comment]
Hi,

I'm sorry, but there's a flaw in the documentation. Since the refactoring of the callbacks, you need to use the default response provided by Jaxon in your callback. Creating your own response won't work anymore.
```php
    $objResponse = jaxon()->getResponse();
```

**Comment by safrick** [comment]
Thank you, it worked perfect!
