### ISSUE TITLE
Using plugins

### ISSUE THREAD

**Issue by theUgluk** [jaxon-php/jaxon-core#7]
This may as well be my own fault, but I can't figure it out, so I hope you're willing to help.

I added my own request handler and added it through the \Jaxon->registerPlugin() method. When I ran this I noticed the \Jaxon\Request\Plugin\CallableObject actually handles the function instead of my own implementation.

After some debugging I discovered that in \Jaxon\Plugin\Manager called $this->aRequestPlugins, an unordered array instead of $this->aPlugins. Replacing this solved the issue (altough it is very ugly looping through all plugins instead of the request plugins).

Is it possible to order the aRequestPlugins array by priority, or is there something I'm doing wrong?

**Comment by feuzeu** [comment]
The plugin name is used as key in the request plugins table. So if you want to use your own implementation of a particular plugin, just give the same name to your plugin, and register as usual.
Each plugin name is returned by its getName() method, and the request plugins are in the src/Request/Plugin dir.

That being said, I would like to know why you need to implement your own request plugin. Are there some missing features in the current one?

**Comment by theUgluk** [comment]
When we used Xajax our programmer wanted to call an entire namespace in Xajax rather than just the classname and function. So he wrote an extension to Xajax to name the classes the whole namespace, but seperated with underscore's instead of backslashes.

E.g. \Jaxon\Plugin\Plugin->getScript() will become Jaxon_Plugin_Plugin.getScript();

Now I'm porting it to Jaxon, and we have some double classnames and function names wich aren't interchangeable, so I either needed to change the Request handler or go through all the code and (rather boringly) just change the names.

Also, this really adds to keeping the jaxon-generated javascript recognizable.

**Comment by feuzeu** [comment]
What if there was an option to use an underscore as class separator in javascript instead of a dot?

**Comment by theUgluk** [comment]
Even then I'd want the whole namespace instead of just the class name

**Comment by feuzeu** [comment]
That's what I'm saying.
Having namespace with dots and class name with underscore is not a usable option.

**Comment by theUgluk** [comment]
Sorry, I misunderstooth you. That'd be an awesome function IMO.

**Comment by feuzeu** [comment]
The feature is added to the 1.0.15 release.
A 4th parameter is added to the $jaxon->addClassDir() method to set the separator character. Accepted values are '.' and '_'.
For example
`$jaxon->addClassDir($directory, $namespace, [], '_');`
A different separator can be used for each class directory.

**Comment by theUgluk** [comment]
Thanks man, you're awesome!

**Comment by feuzeu** [comment]
You're welcome.
