### ISSUE TITLE
example website not working

### ISSUE THREAD

**Issue by seba1rx** [jaxon-php/jaxon-core#70]
This happened a while ago and I thought someone would fix it...

The link provided in the description that goes to the example website is not working, every link in the menu takes you to the example but it loads an error.

Here is the link: https://www.jaxon-php.org/examples.html

and here is an example of the error: https://www.jaxon-php.org/examples/simple/class.html

**Comment by ori-at** [comment]
I just wanted to get started with Jaxon. Having examples would be real helpful, so I'd appreciate if this issue could be fixed. Thanks!

**Comment by feuzeu** [comment]
Hi,

It is fixed now. Sorry for the delay.
However, I had to disable the framework examples.
