### ISSUE TITLE
Notice: Array to string conversion in CallableFunction.php - getHash()

### ISSUE THREAD

**Issue by Waxter81** [jaxon-php/jaxon-core#71]
Hello!

I've just change Jaxon configuration to export JS code to an external file. Everything seems to work fine, but i'm getting this Notice on every page:

```
Notice: Array to string conversion in C:\xxx\vendor\jaxon-php\jaxon-core\src\Request\Plugin\CallableFunction.php on line 147
Method: getHash()
```

My $this->aFunctions contains this Array: 
`Array ( [uploadFile] => Array ( [upload] => 'file-input' ) )`

Thanks in advance

**Comment by feuzeu** [comment]
Fixed.
