### ISSUE TITLE
NOTICE: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by goerob** [jaxon-php/jaxon-core#72]
I have a debugger running and the file Utils/URI.php keep throwing notices in line 143.

`$sURL.= $aURL['path'].@$aURL['query'];`

I know the @-Operator is frequently used to suppress array warnings. So, it's not really a bug. But it would be nice, if this is solved with a isset or similar, to prevent notices even on highest log level.

**Comment by feuzeu** [comment]
Fixed.
