### ISSUE TITLE
Composer Version mismatch?

### ISSUE THREAD

**Issue by goerob** [jaxon-php/jaxon-core#75]
I updated my jaxon lib via composer today. I'm still on version 2.2.x

The update process worked fine.
` - Updating jaxon-php/jaxon-core (v2.2.14 => v2.2.15): Downloading (100%)`

After this I got the error "Call to undefined method Jaxon\Jaxon::readPhpConfigFile()" in my application. I looked in the code and there are a LOT of changes. I think, I got the version 3.x from composer instead of v.2.2.x. This is line 49 from Jaxon.php.
`    private $sVersion = 'Jaxon 3.2.0';`

My composer.json has this line:
`"jaxon-php/jaxon-core": "^2.2",`

I tried to delete and reinstall jaxon but I get the v3.2. every time. Can you have a look into this please? It looks like a version mismatch in composer.

**Comment by idmarinas** [comment]
Try delete dependency and them delete cache of composer
```bash
composer clearcache
```

**Comment by feuzeu** [comment]
Hi,

Sorry, there was an error on the last release on the 2.2.x branch.
It is fixed now, with the new 2.2.16 release.
