### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ori-at** [jaxon-php/jaxon-core#76]
I am attempting to upgrade my old web-page from Xajax to Jaxon, which appears to be fairly straight forward to do. However, I ran into "performance issues": compared to the original Xajax (V0.5) Jaxon's response times are considerably slower. Like when I click on an element that called Xajax code, the response was pretty much immediate, where as with Jaxon I notice a considerable delay (feels like ~250ms). I tested with older versions, and it feels like the newer the version, the slower the response time.

Anyone else experienced this? Is there an explanation for this? Am I doing something wrong?

**Comment by feuzeu** [comment]
Hi,

Can ou share more information about how you measured the performance?
It is hard to answer without even knowing the code running on the server.

There have been numerous changes both on the PHP code running on the server and the javascript code running in the browser.
