### ISSUE TITLE
Unable to submit form

### ISSUE THREAD

**Issue by snoofer** [jaxon-php/jaxon-core#77]
Hi!

Plz check this code:
```
<?php
	require_once ('vendor/autoload.php');	

	$jaxon = jaxon();
	$jaxon->setOption('core.request.uri', $_SERVER['REQUEST_URI'] );

	if ( $jaxon->canProcessRequest() == true ) {
		print "<h1>CanProcess</h1>";
	}
	else {		
		print "<h1>Normal Call</h1>";			
	}	
?>

<form action="" method="post" enctype="multipart/form-data">
	<input id="someText" name="someText" type="text"><br>
	<input type="file" id="upload_example" name="example_file" /><br>
	<br>
	<input type="submit" name="cmdSave" id="cmdSave" value="GO">
</form>
```

When you just press "GO" the canProcessRequest call will return true. But as you can see there isn't any registered methode which should handle an upload. Jaxon should not handle file uploads when there isn't any registered methode with 'upload'.

I think it would be even better if fhe FileUpload Plugin ist not not registered as default or there should be a way to unregister/disable the plugin.

Thanks.

**Comment by feuzeu** [comment]
Hi,

I suggest that you to look at the examples and have a separate file to process Jaxon requests. 
https://github.com/jaxon-php/jaxon-examples/tree/master/web/hello

**Comment by snoofer** [comment]
Hi!

Thanks for the advice. However it is not really a solution in this case since I use this library as a replacement for xajax. I would need to change hundreds of files. Furthermore it is a huge strength of this library to reuse a lot of the code for normal and ajax calls. Just as an example security checks. 
If a really need to separeate the endpoint there is no longer a need for this library for me.

**Comment by feuzeu** [comment]
Hi,

I've released a new tag with a fix.
You can disable the upload plugin by setting the `core.upload.enabled` option to false.

```php
<?php
	require_once ('vendor/autoload.php');	

	$jaxon = jaxon();
	$jaxon->setOption('core.request.uri', $_SERVER['REQUEST_URI'] );
	$jaxon->setOption('core.upload.enabled', false);

	if ( $jaxon->canProcessRequest() == true ) {
		print "<h1>CanProcess</h1>";
	}
	else {		
		print "<h1>Normal Call</h1>";			
	}	
?>
```
