### ISSUE TITLE
$jaxon->callback()->after does not use returned response

### ISSUE THREAD

**Issue by tweb-ix** [jaxon-php/jaxon-core#78]
Returned response of after callback is not appended to the current response as described on https://www.jaxon-php.org/docs/v3x/requests/callbacks.html

**Comment by feuzeu** [comment]
Hi,
Until the issue is fixed, as a workaround, you can use the global response object returned by `jaxon()->getResponse()` in your callbacks, instead of creating a new response object.
Thierry

**Comment by tweb-ix** [comment]
Hi,
thanks for the fast response.
your workaround works for me when changing all registered callbacks (not only after-callback) to the global response object.
Tobias

**Comment by feuzeu** [comment]
Fixed in the [3.3.2](https://github.com/jaxon-php/jaxon-core/releases/tag/v3.3.2) release.
