### ISSUE TITLE
changed behaviour comparing with xajax when mode=synchronous 

### ISSUE THREAD

**Issue by tweb-ix** [jaxon-php/jaxon-core#79]
Hey,

with xajax mode=synchronous could be used to block js execution until request finish.
(XMLHTTPRequest.open has been called with async=false)

yout changed changed this with the following commit:
https://github.com/jaxon-php/jaxon-js/commit/3bb468f176ecc8fde14f459681c28f2c86b4f8b5

how can i restore old xajax behaviour without migrating my old javascript code?

Tobias

**Comment by feuzeu** [comment]
Hi,
I'm sorry, but I don't think it is a good idea to reintroduce a deprecated javascript feature into the library.
I tried to re-implement synchronous requests with queue, and they don't provide the same set of features.
- Synchronous concurrent requests are queued and non blocking (they are asynchronous from the js point of view).
- Asynchronous requests are also queued when there's one or more ongoing synchronous requests.
- You'll not get the return value of the PHP call anymore.
