### ISSUE TITLE
new Response class not found

### ISSUE THREAD

**Issue by frecervantes** [jaxon-php/jaxon-core#80]
Hi Mr Feuzeu, i'm a unmainteined xajax user trying to go forward with jaxon. a simple hello world script containing functions and jaxon calls works perfectly, but taking the function off the script to another file does not work. whats wrong ? thanks in advance.

 the error reported:

<b>Fatal error</b>:  Class 'Response' not found in <b>C:\AppServ\www\Dlink_Jaxon\funcion_holamundo.php</b> on line <b>4</b><br />

file->funcion_holamundo.php

function hello_world($isCaps)
{
    $response = new Response();
    $text = $isCaps == 1 ? 'HELLO WORLD!' : 'Hello World!';
    $response->assign('div2', 'innerHTML', $text);
    return $response;
}

the main script
session_start();

require('vendor/autoload.php');
use Jaxon\Jaxon;
use Jaxon\Response\Response;
$jaxon = jaxon();

// Funciones
/*  
function hello_world($isCaps)
{
    $response = new Response();
    $text = $isCaps == 1 ? 'HELLO WORLD!' : 'Hello World!';
    $response->assign('div2', 'innerHTML', $text);
    return $response;
}
*/
include_once("funcion_holamundo.php");

// registro de funciones
$jaxon->register(Jaxon::USER_FUNCTION, "hello_world");

// Call the Jaxon processing engine  

if ($jaxon->canProcessRequest()) {
    $jaxon->processRequest();
}
$jaxon->setOption('js.app.minify', false);
$jaxon->setOption('core.decode_utf8', true);
$jaxon->setOption('core.debug.on', true);

?>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <meta name="description" content="Incidencias">
    <meta name="author" content="faco">
    <title></title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">\n
    \n
    <?php echo $jaxon->getCss(); ?>\n
    \n
</head>\n

<body>

    <div class="container-fluid">
        <H3>hOLA mUndo</H3>
        <div id='div2'>&nbsp;</div>\n
        <input type="button" class='btn-primary btn-xs' value="Mayus" onclick="jaxon_hello_world(1)" ;return false;" />\n
        <input type="button" class='btn-primary btn-xs' value="Minus" onclick="jaxon_hello_world(0)" ;return false;" />\n
        <button class='btn-primary btn-xs' onclick="<?php print rq()->call('hello_world', 1) ?>">Click Me</button>\n
    </div>\n

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    
    <div id="jaxon-code">
        <?php
        //$jaxon = jaxon();
        echo $jaxon->getJs(), "\n", $jaxon->getScript(), "\n"; //, $jaxon->getCss(), "\n"; getCss ya esta en el head
        //- getCss esta en el Head. ( $jaxon->getScript(true, true) hala los 3 juntos)
        ?>
    </div>
</body>

<?php
// no se si pueden estar fuera del Body pero estan dentro del html
// Insert the Jaxon javascript code into the page
//echo $jaxon->getJs();
//echo $jaxon->getScript();
?>

</html>

**Comment by feuzeu** [comment]
Hi,

You also need to add the `require` and `use` statements in the `funcion_holamundo.php` file, since you are using the `Response` class in the function it declares.

Thierry

**Comment by frecervantes** [comment]
thanks for your answer mr feuzeu, but at this point i believe that the library is up an runing, so, what do i have to require and use again ?
other question sir:  can i configure the prefix to 'xajax_' in order to migrate to jaxon or i need to rewrite every single function instead?
thanks in advance.

**Comment by feuzeu** [comment]
You need to declare all the classes that appear in a file with a `use` statement. That's the way PHP works.

You can change the function prefix using `$jaxon->setOption('core.prefix.function', 'xajax_');`

**Comment by frecervantes** [comment]
is this what you meant mr Thierry?
Realy I'm not an OOP developer, but procedural one. I'm sure it's an easy point, but is a bit hard to get it for me.

function hello_world($isCaps)
{
    require('vendor/autoload.php');
    **_use Jaxon\Response;_**
    use Jaxon\Response\Response;
    $response = new Response();
    $text = $isCaps == 1 ? 'HELLO WORLD!' : 'Hello World!';
    $response->assign('div2', 'innerHTML', $text);
    return $response;
}

the bolded line throws an error.
Parse error: syntax error, unexpected 'use' (T_USE) in C:\AppServ\www\Dlink_Jaxon\funcion_holamundo.php on line 5

**Comment by feuzeu** [comment]
Hi,

You can see an example here: https://github.com/jaxon-php/jaxon-examples/blob/master/web/alias/defs.php.
As a suggestion, you can browse the directory to see how you can organize you code.

```php
require('vendor/autoload.php');
use Jaxon\Response;
use Jaxon\Response\Response;

function hello_world($isCaps)
{
    $response = new Response();
    $text = $isCaps == 1 ? 'HELLO WORLD!' : 'Hello World!';
    $response->assign('div2', 'innerHTML', $text);
    return $response;
}

```
