### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by kskelton2021** [jaxon-php/jaxon-core#82]
Can someone help me figure this out?

Im using jaxon 3.2 and i am able to upload photos without a problem. 

Couple issues: 
1. Im unable to set default file types even though i put them in correct i believe. It still uploads other files like pdf when i test it.
$jaxon->setOption('upload.default.extensions', 'image/gif, image/jpeg');

2. Retrieving uploaded files. I have manipulated my code to get the file and move it to another folder, but I can see bugs in my code that can create problems internally for me. I want to retrieve the uploaded data using the default jaxon method. This is my test code where im able to see the data, but can't get past it to pull the individual data out:

class Upload
{
    public function uploadedFile()
	{
		$response = new Response;
	
		// Get uploaded files
		$aUploadedFiles = jaxon()->upload()->files();
		
		$array = $aUploadedFiles['image'][0];
		$array = '<pre>'.print_r($array, true).'</pre>';
		$array = json_decode(json_encode($array), true);
		
		$response->assign("aUploadedFiles", "innerHTML", $array);
		
		return $response;
	}
	
}

When I upload, this is what i see:

Jaxon\Request\Support\UploadedFile Object
(
    [sType:protected] => image/gif
    [sName:protected] => Test_file_300x250
    [sFilename:protected] => Test_file_300x250.gif
    [sPath:protected] => /path/to/upload/61299617d4294/Test_file_300x250.gif
    [sSize:protected] => 111809
    [sExtension:protected] => gif
)

Can someone show me how to get the individual data out?

Thanks in advance

**Comment by feuzeu** [comment]
Hi,

The `extensions` options must be an array. Try this.
```php
$jaxon->setOption('upload.default.extensions', ['image/gif', 'image/jpeg']);
```

**Comment by kskelton2021** [comment]
Thanks for your quick response.

The files are in the directory specified in the configuration, however, Jaxon creates another folder with a randomized name in the directory specified in the configuration folder and places the uploaded file there.
$jaxon->setOption('upload.default.dir', '/path/to/upload');

My problem is, to be able to access the uploaded file, I would need to know what the randomized folder name is. That where this comes in:

Get uploaded files
$aUploadedFiles = jaxon()->upload()->files();

I am trying to grab the data out of the array immediately after it is uploaded so i can work with the uploaded file.

My code looks like this:

class Upload
{
public function uploadedFile()
{
$response = new Response;

	// Get uploaded files
	$aUploadedFiles = jaxon()->upload()->files();
	
	$array = $aUploadedFiles['image'][0];
	$array = '<pre>'.print_r($array, true).'</pre>';
	$array = json_decode(json_encode($array), true);
	
	$response->assign("aUploadedFiles", "innerHTML", $array);
	
	return $response;
}
}

which output this after upload:

Jaxon\Request\Support\UploadedFile Object
(
[sType:protected] => image/gif
[sName:protected] => Test_file_300x250
[sFilename:protected] => Test_file_300x250.gif
[sPath:protected] => /path/to/upload/61299617d4294/Test_file_300x250.gif
[sSize:protected] => 111809
[sExtension:protected] => gif
)

Im trying to grab this data above, specifically the sPath from the Object array.

Thanks.

**Comment by feuzeu** [comment]
Please read the upload doc at https://www.jaxon-php.org/docs/v3x/registrations/upload.html.

_The call to jaxon()->upload()->files() returns an array where the key is the name attribute of the input field, and the value is an array of objects of class `Jaxon\Request\Support\UploadedFile`, each representing an uploaded file._

The variable you called `$array` is actually an object of class https://github.com/jaxon-php/jaxon-core/blob/master/src/Request/Support/UploadedFile.php.

So you must have something like this.
```php
$aUploadedFiles = jaxon()->upload()->files();

$images = $aUploadedFiles['image'];
$html = '';
foreach($images as $image)
{
    $array = [
        'type' => $image->type(),
        'name' => $image->name(),
        'filename' => $image->filename(),
        'extension' => $image->extension(),
        'size' => $image->size(),
        'path' => $image->path(),
    ];
    // Same as $array = $image->toTempData();
    $html .= '<pre>'.print_r($array, true).'</pre>';
}
```

**Comment by kskelton2021** [comment]
Thank you so much, I really appreciate your help. It all works. I am now where I need to be to finish my coding.

Thank you.

**Comment by kskelton2021** [comment]
One last thing, how do you display errors in the upload? For example, if the wrong file type is uploaded or any other possible upload error? I would like to be able to display the error to the user.  I been searching jaxon-php site but not able to find the solution.

Thanks.

**Comment by feuzeu** [comment]
You must set a callback for invalid requests as described here: https://www.jaxon-php.org/docs/v3x/requests/callbacks.html.
You'll need to define and return a new response in your callback function if you want to return data to your user.

**Comment by feuzeu** [comment]
> Thank you so much, I really appreciate your help. It all works. I am now where I need to be to finish my coding.
> 
> Thank you.

You're welcome. Please consider giving a star to the package :-)

**Comment by kskelton2021** [comment]
Can you tell me what im doing wrong?

```
class Upload
{
    public function uploadedFile()
	{
		// Get uploaded files
		$aUploadedFiles = jaxon()->upload()->files();
		$images = $aUploadedFiles['image'];
		
		$html = '';
		foreach($images as $image)
		{
		    $array = [
		        'type' => $image->type(),
		        'name' => $image->name(),
		        'filename' => $image->filename(),
		        'extension' => $image->extension(),
		        'size' => $image->size(),
		        'path' => $image->path(),
		    ];
		    
		    $target = $array['path'];

			//Upload script
			move_uploaded_file($_FILES["image"]["tmp_name"], $target);
			list($width, $height) = getimagesize($target); //Get Photo Dimensions
			$modwidth = ($width >= '815')? '815' : (($width < '815')? $width : null);
			$diff = $width/$modwidth;
			$modheight = $height/$diff;
			
			$save = $_SERVER['DOCUMENT_ROOT'] . "/upload/".$array['filename'];
			
			$tn = imagecreatetruecolor($modwidth, $modheight); 
			$image = imagecreatefromjpeg($target); 
			imagecopyresampled($tn, $image, 0, 0, 0, 0, $modwidth, $modheight, $width, $height);
			imagejpeg($tn, $save, '95');
			
			//Remove files and folder after processing
			unlink($target);
			//rmdir($target);
			
			imagedestroy($tn);
			imagedestroy($image);
		}
		
		$jaxon->callback()->invalid(function($sMessage) {
			
			$response = new Response;
		
			$response = jaxon()->getResponse();
			$response->assign("aUploadedFiles", "innerHTML", $sMessage);
		
		return $response;
		});
	}
}

```
Im not able to get the invalid callback to work. I tried to look up examples, but still couldn't get it to work.

**Comment by feuzeu** [comment]
The callbacks are defined at the same place as the other options.

```php
$jaxon->setOption('upload.default.extensions', ['image/gif', 'image/jpeg']);
$jaxon->callback()->invalid(function($sMessage) {
    // $response = new Response;
    $response = jaxon()->getResponse();
    $response->assign("aUploadedFiles", "innerHTML", $sMessage);
    return $response;
});
```

**Comment by kskelton2021** [comment]
Thanks.

This is my configuration setup.  However when I test for error, I didn't get a response on the page.

```
//Jaxon
$jaxon = jaxon();
$jaxon->setOption('core.debug.on', 0);
$jaxon->setOption('upload.default.dir', $_SERVER['DOCUMENT_ROOT'] . '/upload');
$jaxon->setOption('upload.default.extensions', ['jpeg', 'jpg']);

$jaxon->callback()->invalid(function($sMessage) {
    $response = jaxon()->getResponse();
    $response->assign("aUploadedFilez", "innerHTML", $sMessage);
    return $response;
});

```

**Comment by feuzeu** [comment]
A reason why this may not work is that the config is not applied when processing Jaxon requests.

So you need to make sure that this code is also called before `$jaxon->processRequest()`, and not only when you display the initial page.

**Comment by kskelton2021** [comment]
I created a test page and it functions as far as uploading, however not the callbacks. See entire page code below:

```
<?php
//Jaxon
require ($_SERVER['DOCUMENT_ROOT'] .'/third-party-software/jaxon/3.2.1/autoload.php');

use Jaxon\Jaxon;
use Jaxon\Response\Response;

class Upload
{
    public function uploadedFile()
	{
		// Get uploaded files
		$aUploadedFiles = jaxon()->upload()->files();
		$images = $aUploadedFiles['image'];
		$html = '';
		foreach($images as $image)
		{
		    $array = [
		        'type' => $image->type(),
		        'name' => $image->name(),
		        'filename' => $image->filename(),
		        'extension' => $image->extension(),
		        'size' => $image->size(),
		        'path' => $image->path(),
		    ];
		$html .= '<pre>'.print_r($array, true).'</pre>';
		}
	
	$response = new Response;
	$response->assign("aUploadedFiles", "innerHTML", $html);
	return $response;
	}	
}

$jaxon = jaxon();
$jaxon->setOption('core.debug.on', 0);
$jaxon->setOption('upload.default.dir', $_SERVER['DOCUMENT_ROOT'] . '/upload');
$jaxon->setOption('upload.default.extensions', ['jpeg', 'jpg']);

$jaxon->callback()->invalid(function($sMessage) {
    $response = jaxon()->getResponse();
    $response->assign("aUploadedFilez", "innerHTML", $sMessage);
    return $response;
});

$jaxon->register(Jaxon::CALLABLE_CLASS, Upload::class, [
    'uploadedFile' => [
        'upload' => "'testUpload'"
    ]
]);

if($jaxon->canProcessRequest()){
    $jaxon->processRequest();	
}

//Bootstrap
require ($_SERVER['DOCUMENT_ROOT'] .'/third-party-software/bootstrap/5.1.0/autoload.php');
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes">
	<meta name="description" content="">
	<meta NAME="keywords" CONTENT="">
	<meta http-equiv="imagetoolbar" content="no">
	<title>Test Uploading with feedback!</title>
	<link rel="stylesheet" href="third-party-software/bootstrap/5.1.0/twbs/bootstrap/dist/css/bootstrap.min.css">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div id="aUploadedFiles" class="col-12 p-0 mt-auto"></div>
				<div id="aUploadedFilez" class="col-12 p-0"></div>
				<form method="post" enctype="multipart/form-data" onsubmit="JaxonUpload.uploadedFile(jaxon.getFormValues('imgtestupload'));return false;" id="imgtestupload" class="p-0">
					<div class="form-group row m-0 mb-2 mt-5">
						<label for="inputCategory" class="col-sm-2 col-form-label px-0">Upload Image File</label>
						<div class="col-8 col-sm-4 p-0"><input type="file" class="form-control" id="testUpload" aria-describedby="inputUploadFile" name="image[]" multiple="multiple" required></div>
						<div class="col-4 col-sm-2 pr-0"><input type="submit" class="btn btn-primary btn-block" value="Upload" name="action"></div>
						<div class="col-sm-12 text-muted pt-2 px-0"><small>Only JPEG images are accepted. Your file size must be less than 2MB.</small></div>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>

<?php
echo $jaxon->getJs();
echo $jaxon->getScript();
?>

</html>

```

**Comment by feuzeu** [comment]
The 3.3.2 release fixed the issue #78, where the callback response was not added into the final response.
I suggest you to upgrade to a newer version on the library.

**Comment by kskelton2021** [comment]
I will try that... I actually tried 3.5.1 and upload stopped working... I didn't make any changes, just updated Jaxon and files were no longer uploading.

**Comment by feuzeu** [comment]
Sorry, there were changes in the config format in 3.5.0 that are not yet documented.
Try with the latest 3.4.x.

**Comment by kskelton2021** [comment]
got it. I just actually upgraded to 3.3.3 and callback is now working... I will go up to 3.4.x so that im fully up to date. Thank you so much for your assistance... I greatly appreciate it.

**Comment by feuzeu** [comment]
You're welcome!

**Comment by kskelton2021** [comment]
Before I go, I upgraded to 3.4.1 and all is well. Just one thing, the error message that came back says "Upload is not allowed for file with extension :extension." should the second :extension be the actual file extension?

**Comment by feuzeu** [comment]
Of course. I'll check it.

**Comment by kskelton2021** [comment]
Cool.

A few more errors i found with the error messages:
when the min file size is set and the file is smaller than the set minimum, Jaxon display the following message:
"errors.upload.min-size"

When the max file size is set, and the file exceeds it, Jaxon display the following message:
"Upload is not allowed for file of size 175382. Too small."

I think it should say "Too Big" since the file is bigger than the max limit.

Thanks.

**Comment by feuzeu** [comment]
There were typos in the validation code and translation keys.

They are fixed in the [3.4.2](https://github.com/jaxon-php/jaxon-core/releases/tag/v3.4.2) and [3.5.2](https://github.com/jaxon-php/jaxon-core/releases/tag/v3.5.2) releases.

If you choose to move to the 3.5.2 version, you'll need to change the registration code to this.
```php
$jaxon->register(Jaxon::CALLABLE_CLASS, Upload::class, [
    'functions' =>
        'uploadedFile' => [
            'upload' => "'testUpload'"
        ]
    ]
]);
```

I also suggest, whichever version you install, to use the `include` option and move your classes to separate files.

3.5
```php
$jaxon->register(Jaxon::CALLABLE_CLASS, Upload::class, [
    'include' => __DIR__ . '/upload.php',
    'functions' =>
        'uploadedFile' => [
            'upload' => "'testUpload'"
        ]
    ]
]);
```

3.4
```php
$jaxon->register(Jaxon::CALLABLE_CLASS, Upload::class, [
    'include' => __DIR__ . '/upload.php',
    'uploadedFile' => [
        'upload' => "'testUpload'"
    ]
]);
```

**Comment by kskelton2021** [comment]
I updated to both 3.4.2 and 3.5.2 and uploads worked as expected, but only without the include.

With the include added, the page refreshes and show a blank page on a successful upload and added a tmp folder with a .json file in it, and on a upload restriction trigger, it refreshes the page and displays debug coded language.

**Comment by feuzeu** [comment]
I successfully tested it with this code in the `Upload.php` file.

```php
<?php

use Jaxon\Response\Response;

class Upload
{
    public function uploadedFile()
    {
        // Get uploaded files
        $aUploadedFiles = jaxon()->upload()->files();
        $images = $aUploadedFiles['image'];
        $html = '';
        foreach($images as $image)
        {
            $array = [
                'type' => $image->type(),
                'name' => $image->name(),
                'filename' => $image->filename(),
                'extension' => $image->extension(),
                'size' => $image->size(),
                'path' => $image->path(),
            ];
            $html .= '<pre>'.print_r($array, true).'</pre>';
        }

        $response = new Response;
        $response->assign("aUploadedFiles", "innerHTML", $html);
        return $response;
    }
}
```

And this code to register it.
```php
        $jaxon->register(JaxonCore::CALLABLE_CLASS, 'Upload', [
            'include' => __DIR__ . '/Upload.php',
            'functions' => [
                'uploadedFile' => [
                    'upload' => "'file-select'"
                ]
            ]
        ]);
```

**Comment by kskelton2021** [comment]
Ok. I'm on 3.5.2 and I was able to add the include into the register as suggested and it all works like a charm. I believe I have a better understanding now with how to use Jaxon more efficiently. 

Thank you for taking the time with me, I greatly appreciate it and keep up the great work on Jaxon.

**Comment by feuzeu** [comment]
Hi,

Here are some tips you may find useful.

Move your Jaxon classes to a dir, and export them in one single step.
https://www.jaxon-php.org/docs/v3x/registrations/directories.html
You'll not need to change your settings any time you add or remove a class.
You can even have your classes namepaced, and the js classes will be named accordingly.
https://www.jaxon-php.org/docs/v3x/registrations/namespaces.html

Make your Jaxon classes inherit from `Jaxon\CallableClass` (https://github.com/jaxon-php/jaxon-core/blob/master/src/CallableClass.php).
Jaxon will then initialize your classes with a response, the jquery plugin, a request factory, a view renderer, and even a paginator.
https://www.jaxon-php.org/docs/v3x/advanced/classes.html

You can a have a look at this repo to see an example of how these features are used.
https://github.com/lagdo/jaxon-dbadmin/tree/main/app
It's a brand new project I'm working on.
