### ISSUE TITLE
Jaxon behind load balancer -  needs to detect X-FORWARDED proxy settings

### ISSUE THREAD

**Issue by khoosys** [jaxon-php/jaxon-core#83]
Make sure load balancer is sending through HTTP_X_FORWARDED_PROTO and HTTP_X_FORWARDED_POR, then 

In URI.php replace line 70 to [port] with :

        // Fill in the empty values
        if(empty($aURL['scheme']))
        {
            if(!empty($_SERVER['HTTP_SCHEME']))
            {
                $aURL['scheme'] = $_SERVER['HTTP_SCHEME'];
            }
            else
            {
				$aURL['scheme'] = 'http';
				if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
					$aURL['scheme'] = 'https';
				}
				elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
					$aURL['scheme'] = 'https';
				}
            }
        }

        $this->getHostFromServer($aURL, 'HTTP_X_FORWARDED_HOST');
        $this->getHostFromServer($aURL, 'HTTP_HOST');
        $this->getHostFromServer($aURL, 'SERVER_NAME');
        if(empty($aURL['host']))
        {
            throw new \Jaxon\Exception\URI();
        }

        if(empty($aURL['port'])) {
        	if (!empty($_SERVER['HTTP_X_FORWARDED_PORT']))
        	{
				$aURL['port'] = $_SERVER['HTTP_X_FORWARDED_PORT'];
        	} 
        	else if (!empty($_SERVER['SERVER_PORT']))
        	{
				$aURL['port'] = $_SERVER['SERVER_PORT'];
			}
		}

**Comment by feuzeu** [comment]
You can change the request uri to whatever value you want.
```php
// Request processing URI
$jaxon->setOption('core.request.uri', $uri);
```

**Comment by khoosys** [comment]
I saw that. But doing that rather defeats the purpose of this class and with a few hundred sites using this call it is much easier to change the detector than to alter the calls to handle it. The only reason for wanting it on the code branch is to save us having to reinsert the fix every time we update composer.
