### ISSUE TITLE
Missing clear PHP version support matrix on web site and README.md

### ISSUE THREAD

**Issue by frameworker2019** [jaxon-php/jaxon-core#85]
It's a little bit unclear what PHP versions are eligible to be supported by Jaxon. 
Neither on the web site nor the installation doc shows a clear requirement.

The Readme.md on GitHub points out support up to 7.x, but the some commits after 3.5.1 shows php8 comments.
I suggest a more clear statement on the website as well in the README.

For example its totally unclear whether Jaxon is working with installations based on PHP 5.x. There are many companies in the world which are have very restrictive upgrade plans, so it would be good to know what exactly Jaxon's min/max requirments are.

**Comment by feuzeu** [comment]
As stated in the readme, the library runs on PHP versions 5.4 to 7.X.

I started a new branch to work on PHP8 support, hence the commits. But since nobody asked for it, there's no release based on this branch, and no official support of PHP8.
