### ISSUE TITLE
Examples cannot be accessed due to SSL error

### ISSUE THREAD

**Issue by frameworker2019** [jaxon-php/jaxon-core#86]
It seems some SSL certificates ran out of time.
https://www.jaxon-php.org/examples/simple/hello.html

file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

**Comment by feuzeu** [comment]
Working on it. Meanwhile, you can check the example code in this repo: https://github.com/jaxon-php/jaxon-examples

**Comment by feuzeu** [comment]
You can also see a real world use of the library in this package: https://github.com/lagdo/jaxon-dbadmin/tree/main/app
Or these
- https://github.com/lagdo/jaxon-supervisor
- https://github.com/lagdo/twitter-feed
- https://github.com/lagdo/polr-admin
