### ISSUE TITLE
Fatal error: Uncaught Error: Interface 'Psr\Log\LoggerAwareInterface' not found

### ISSUE THREAD

**Issue by frameworker2019** [jaxon-php/jaxon-core#87]
I'm trying to use Jaxon without using the composer and getting this error when including Jaxon.php.

**Comment by feuzeu** [comment]
I you want to use the package without Composer, you'll need to manually do all what Composer does: install the right version of the required packages, and setup the autoloading. It can be very complicated.
It is simpler to first install the Jaxon with Composer on a single host, then copy the `vendor` dir somewhere into your application.
You'll then need to include only the `vendor/autoload.php` file.

**Comment by frameworker2019** [comment]
This is a good idea and it works.
