### ISSUE TITLE
setOption js.lib.uri seems not to recognize if the passed URI doesn't exist

### ISSUE THREAD

**Issue by frameworker2019** [jaxon-php/jaxon-core#88]
In Xajax if the supporting JS file could not be loaded, an error alert was pushed.
In Jaxon if you pass a path which doesn't exist for the option mentioned above, nothing happens.
I've tried also to surround the initialization part with try/catch, but teh result is still the same.
A wrong path is not recognized.

**Comment by feuzeu** [comment]
Since the js code is now provided in a separate package, the PHP code cannot check if it is actually loaded.
You need to check it by yourself, or load the js libs from a CDN (for example https://cdn.jsdelivr.net/gh/jaxon-php/jaxon-js@3.3/dist/jaxon.core.js), as Jaxon does by default.

**Comment by frameworker2019** [comment]
So if I set the option js.lib.uri, does Jaxon automatically load the file or is this the projects cup of tea?

**Comment by feuzeu** [comment]
The Jaxon js libs are static files. It is then simpler to have them delivered by a web server.
You set the `js.lib.uri` option accordingly, and the browser loads them from a web server. There's no interaction with our PHP app.

You can also load them from the CDN. It's even easier; just don't set the option.

**Comment by frameworker2019** [comment]
This works not for me. Often you have production settings where no internet connection is given. So I must include this file statically in my project and Jaxon should use the local version.

You didn't answer my question: After setting this option, is Jaxon load that file automatically? If not, the project must include the file by script tags. I cannot see in your doc whether this is required or not.

The doc says:
> Jaxon requires the [jaxon-js](https://github.com/jaxon-php/jaxon-js) javascript library to be loaded into the HTML page to operate properly.
>By default, the javascript library files are loaded from the [jsDelivr CDN](https://www.jsdelivr.com/package/gh/jaxon-php/jaxon-js).

Jaxon "requires" the file, but it's also load automatically a default version from web. It's not clear what happens if the default behavior is overidden by the js.lib.uri option.

**Comment by feuzeu** [comment]
Jaxon requires the file to be loaded in the web page, what you need to do from your web server or the CDN.

**Comment by feuzeu** [comment]
I think there's a need for more clarification on this issue.

Unlike Xajax, Jaxon has separated the the javascript files of its library from the javascript code which it generates for callables functions and classes.

The former are provided in the [jaxon-js package](https://github.com/jaxon-php/jaxon-js), and need to be loaded from the CDN or installed on a web server prior to using the library.
The corresponding URI must be set in the library using the `js.lib.uri` option. This option indicates a directory, and Jaxon will append the filenames to its value. Depending on the config, the names can be those of the minified files or not.
The `$jaxon->getJs()` function returns the corresponding HTML tags. 

Now for the js code Jaxon generates for the callable classes and functions are, there are four config options.
If the `js.app.export` option value is set to false, Jaxon will return the raw js code, to inserted in the HTML code of the web page.
If the `js.app.export` option value is set to true, then Jaxon will generate a file under the directory given by the `js.app.dir` option, and use the `js.app.uri` option to generate and return the HTML tags to load that file. It is your responsibility to setup your web server to load that file, as you already did with Xajax. If the `js.app.minify` is set to true, Jaxon will also minify the file.
The `$jaxon->getScript()` function returns the corresponding HTML tags.
