### ISSUE TITLE
Jaxon initialization problems

### ISSUE THREAD

**Issue by frameworker2019** [jaxon-php/jaxon-core#89]
Circumenting the need of [composer](https://github.com/jaxon-php/jaxon-core/issues/87) I pull the autoload.php inside the vendor directory.
This works so far.

1. Comparing to Xajax, I cannot see that the jaxon.core.js library is loaded when the site is loaded. 

In Xajax the source text looks like this for example:
```
<!doctype html><html lang="[en]()"><head>
<script type="[text/javascript]()" charset="[UTF-8]()">
/* <![CDATA[ */
try { if (undefined == xajax.config) xajax.config = {}; } catch (e) { xajax = {}; xajax.config = {}; };
xajax.config.requestURI = "http://localhost:83/pj/deploy/main.phtml";
xajax.config.statusMessages = false;
xajax.config.waitCursor = true;
xajax.config.version = "xajax 0.5";
xajax.config.legacy = false;
xajax.config.defaultMode = "asynchronous";
xajax.config.defaultMethod = "POST";
/* ]]> */
</script>
<script type="[text/javascript]()" src="[../../framework/xajax/xajax_js/xajax_core.js](view-source:http://localhost:83/framework/xajax/xajax_js/xajax_core.js)" charset="[UTF-8]()"></script>
<script type="[text/javascript]()" charset="[UTF-8]()">
/* <![CDATA[ */
window.setTimeout(
 function() {
  var scriptExists = false;
  try { if (xajax.isLoaded) scriptExists = true; }
  catch (e) {}
  if (!scriptExists) {
   alert("Error: the xajax Javascript component could not be included. Perhaps the URL is incorrect?\nURL: ../../framework/xajax/xajax_js/xajax_core.js");
  }
 }, 2000);
/* ]]> */
</script>

<script type="[text/javascript]()" charset="[UTF-8]()">
/* <![CDATA[ */
xajax_foo = {};
xajax_foo.doClick = function() { return xajax.request( { xjxcls: 'foo', xjxmthd: 'doClick' }, { parameters: arguments } ); };
/* ]]> */
</script>
```
You can see the initialized xajax object, the JS check region whether the included JS exists and the registered class with one method in the example.
Even when I initialize Jaxon in similiar way like Xajax:
```
$jaxon = jaxon();

$jaxon->setOption('core.encoding', 'iso-8859-15');
$jaxon->setOption('core.decode_utf8', true);
$jaxon->setOption('js.lib.uri', X_FRAMEWORK_PATH . '/lib/jaxon.core.min.js');
$jaxon->setOption('js.app.export', false);
$jaxon->setOption('core.prefix.class', 'xajax');
...snip
$jaxon->register('CallableClass', foo::class);
...snip
echo $jaxon->getScript();
```

the source shows nothing more than the HTML code of the site. I cannot see any JS code produced by Jaxon.

The PHP version is 7.4.22.

**Comment by feuzeu** [comment]
The corresponding documentation is here: https://www.jaxon-php.org/docs/v3x/registrations/javascript.html

There are 3 separate functions to output the CSS, Js and HTML codes, because they can be inserted at different places in the web page.
This is the signature of the `getScript` method.
```php
public function getScript(bool $bIncludeJs = false, bool $bIncludeCss = false)
```
So if you want the same output as with Xajax, you need to call `$jaxon->getScript(true, true);`.

**Comment by frameworker2019** [comment]
Nothing changed. 
I can see only some empty lines that are produced.

I research the code base and changed the option settings to pass only the URI path instead the full file name:
```
$jaxon->setOption('js.lib.uri', X_FRAMEWORK_PATH . '/lib');
```

Is this correct?

Why I can't see that Jaxon is pulling the jaxon.core.js file? It does not happen.

**Comment by frameworker2019** [comment]
Can you post your phpinfo() setting? Probably there's a difference which affects the behavior.

**Comment by feuzeu** [comment]
> Nothing changed. I can see only some empty lines that are produced.
> 
> I research the code base and changed the option settings to pass only the URI path instead the full file name:
> 
> ```
> $jaxon->setOption('js.lib.uri', X_FRAMEWORK_PATH . '/lib');
> ```
> 
> Is this correct?
> 
> Why I can't see that Jaxon is pulling the jaxon.core.js file? It does not happen.

I didn't notice this line. I think the error is there.
```
$jaxon->setOption('js.lib.uri', X_FRAMEWORK_PATH . '/lib');
```
The value of this option must be an URL, and you passed a path, thus the issue.
Pass an URL to this option, and then make sure your web server is configured to redirect this URL to the X_FRAMEWORK_PATH dir.

**Comment by frameworker2019** [comment]
I changed the option like this:
```
$jaxon->setOption('js.lib.uri', 'http://localhost/framework/lib/jaxon.core.min.js');
```

But the reload shows still the the file will not automatically pulled by Jaxon. If I paste the URI in a new browser tab, I can see the content, so the URI is correct on my side.

I've tried also
```
$jaxon->setOption('js.lib.uri', 'http://localhost/framework/lib');
with
$jaxon->setOption('js.app.minify', true);
```
because I've seen somewhere in the code the you construct the file name jaxon.core .js/.min.js with the appropriate extension controlled by the minify flag.

But all of this seems not to help.

**Comment by frameworker2019** [comment]
Even when I include jaxon.core.min.js manually, the getScript() call returns only empty lines. I suppose it's probably due to different PHP compilation settings. 
I research the code and integrate some simple debug trails to control whether the methods - after ->register() for example - are called properly.
Without to understand what the code is doing, this is quite a simple check. I cannot do more at this point.
Because no errors will be thrown by Jaxon (error_reporting(-1)) for the small initialization example above, I assume Jaxon processed the simple example correctly.
So at the moment I think that Jaxon requires a special PHP setting which I currently not have.

I compile PHP like this because my production requires still monolithic shared objects:
```
./configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --sysconfdir=/private/etc --with-apxs2=/usr/bin/apxs --disable-cli --with-config-file-path=/etc --with-libxml-dir=/usr --with-kerberos=/usr --with-zlib=/usr --enable-bcmath --with-bz2=/usr --enable-calendar --disable-cgi --enable-dba --enable-exif --with-gd --with-icu-dir=/usr --with-ldap=/usr --enable-mbstring --enable-mbregex --enable-shmop --enable-sockets --enable-suhosin --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --with-xmlrpc --with-iconv-dir=/usr --enable-zend-multibyte --enable-zip --with-pcre-regex=/usr --with-pgsql=/usr --with-pdo-pgsql=/usr --without-sqlite3 --without-pdo-sqlite
```

And the resulting phpinfo:
[PHP 7.4.22 - phpinfo().html.gz](https://github.com/jaxon-php/jaxon-core/files/8140658/PHP.7.4.22.-.phpinfo.html.gz)

**Comment by feuzeu** [comment]
```
$jaxon->setOption('js.lib.uri', 'http://localhost/framework/lib/');
```
Then the `$jaxon->getJs()` will return the HTML tags to load the js files, what the browser will do.

**Comment by frameworker2019** [comment]
Okay, I dropped every link to my environment and create this basic example:

```
<?
error_reporting(-1);
require_once ('Jaxon/vendor/autoload.php')

class foo {

    public function doClick() {
    }
}

$jaxon = jaxon();

$jaxon->setOption('core.encoding', 'utf-8');
$jaxon->setOption('core.decode_utf8', true);
$jaxon->setOption('js.lib.uri', 'http://localhost/framework/lib');
$jaxon->setOption('js.app.export', false);
$jaxon->setOption('js.app.minify', true);
$jaxon->setOption('core.prefix.class', 'xajax_');

echo $jaxon->getJS();

$jaxon->register('CallableClass',foo::class);

echo $jaxon->getScript(true,true);

?>
```

In this case I get the warning

>Warning: include(/plugins/includes.js.php): failed to open stream: No such file or directory in /var/www/html/pj/deploy/Jaxon/src/Utils/Template/Engine.php on line 102

When I look  below Jaxon/src or the vendor directory I cannot find any directory which name is called 'plugins'. There's a Jaxon/src/Plugin instead.

**Comment by frameworker2019** [comment]
Found it, the composer ignored the templates directory. It's weird. I copy the subbdirectory Templates/plugins to /var/www/html the doc root.
Engine.php evaluates $_sPath whcih is obv. an absoliute path just behind the doc root.
Checking http://localhost/plugins/include.js.php => OK (this error because out of context, but hey)

But Engine.php still fails that it cannot include this file. 
BTW is there any possibility to prefix the path from which the plugins can be pulled?
But for this concrete test scenario, I don't understand why the script cannot be included.

**Comment by frameworker2019** [comment]
OK, no pains no gains. I had to change Enging.php like this to get your stuff working:
```
   // Render the template
        $cRenderer = function($_sPath) {
            ob_start();
            include(X_FRAMEWORK_URI . '/Jaxon/src/' . $_sPath);
            return ob_get_clean();
        };
```

Now the jaxon.core.js is pulled, but twice. But I can now see the JS generated code produced by Jaxon itself.
I will take a closer look to get rid of this interim test scenario.

**Comment by frameworker2019** [comment]
Removing the getJS() forces the jaxon.core.js to be pulled only once. But I cannot see the registered class method JS stuff for the foo class. This is the test script:

```
<?
error_reporting(-1);
include('pj.php');


class foo {

    public function doClick() {
    }
}

$jaxon = jaxon();

$jaxon->setOption('core.encoding', 'utf-8');
$jaxon->setOption('core.decode_utf8', true);
$jaxon->setOption('js.lib.uri', X_FRAMEWORK_URI . '/lib');
$jaxon->setOption('js.app.export', false);
$jaxon->setOption('core.prefix.class', 'xajax_');

$jaxon->register('CallableClass',foo::class);

echo $jaxon->getScript(true,true);

?>
```

And this the output:

```
<script type="[text/javascript]()"  charset="[UTF-8]()">
/* <![CDATA[ */
try {
    if(typeof jaxon.config == undefined)
        jaxon.config = {};
}
catch(e) {
    jaxon = {};
    jaxon.config = {};
};

jaxon.config.requestURI = "http://localhost/pj/deploy/test.phtml";
jaxon.config.statusMessages = false;
jaxon.config.waitCursor = true;
jaxon.config.version = "Jaxon 3.8.0";
jaxon.config.defaultMode = "asynchronous";
jaxon.config.defaultMethod = "POST";
jaxon.config.responseType = "JSON";








jaxon.dom.ready(function() {





    jaxon.command.handler.register("jquery", function(args) {
        jaxon.cmd.script.execute(args);
    });

    jaxon.command.handler.register("bags.set", function(args) {
        for (const bag in args.data) {
            jaxon.ajax.parameters.bags[bag] = args.data[bag];
        }
    });
});

/* ]]> */
</script>
```

**Comment by frameworker2019** [comment]
Got it to work. For people who are constrained with projects which are not using the composer this the plan to get it running:

1. Create the vendor directory via composer.phar
2. Copy vendor directory to specific project root
3. Copy jaxon-core/templates/support,plugins,pagination to project root
4. Interims change Jaxon/src/Utils/Template/Engine.php line #101 to change the prefix of the template renderer

Point 4. could be an minor enhancement to provide the include prefix via option.

@feuzeu last question: Where in the code base is the place for getting the methods of a registered class?

**Comment by feuzeu** [comment]
For me the points 1 and 2 are ok.

You don't need to change the template location, and you don't need to have access to the templates from the browser. They are only used internally by the library.
Your change in the Template.php file may cause the templating feature not to work anymore. You will not be able to load templates from other directories.
The path to the templates dir is set here, and unless this path is incorrect, you don't need to change the code:
https://github.com/jaxon-php/jaxon-core/blob/0602c9cd0a4530e38f1ac603d0221a074dd88de5/src/Utils/DI/Container.php#L90

**Comment by feuzeu** [comment]
> @feuzeu last question: Where in the code base is the place for getting the methods of a registered class?

I don't understand the question. What do you want to do actually?

**Comment by frameworker2019** [comment]
> > @feuzeu last question: Where in the code base is the place for getting the methods of a registered class?
> 
> I don't understand the question. What do you want to do actually?

To have a more granular control what for methods will be considered for generating JS code of each one. The doc says only public methods will be considered. But maybe I have private or protected methods which are also should be affected by the register process.
On the other hand, I could have public methods which are **not** to be considered when registering the class.
Xajax also didn't has such an "exclude" feature, so I changed the Xajax code exactly on the spot of the code where Xajax queries the class to get the methods. Xajax passed the object reference when registering the class. I called a hook on each object which in turn provides an array with method names to register. A simple and working solution.
Jaxon just pass name of the class when registered. How do you get the methods a class have and where in the code base can I find the place when this happens?

**Comment by frameworker2019** [comment]
>If you don't want some public methods to be in the js class, pass them in an array to the protected option.

Thanks, this works like a charm.



> The path to the templates dir is set here, and unless this path is incorrect, you don't need to change the code:
> 
> https://github.com/jaxon-php/jaxon-core/blob/0602c9cd0a4530e38f1ac603d0221a074dd88de5/src/Utils/DI/Container.php#L90

Can you provide $sTemplateDir as an option in a future version?

**Comment by feuzeu** [comment]
> > The path to the templates dir is set here, and unless this path is incorrect, you don't need to change the code:
> > https://github.com/jaxon-php/jaxon-core/blob/0602c9cd0a4530e38f1ac603d0221a074dd88de5/src/Utils/DI/Container.php#L90
> 
> Can you provide $sTemplateDir as an option in a future version?

This directory is reserved for the library templates. You need to register your own directories for your templates.
https://www.jaxon-php.org/docs/v3x/advanced/views.html

Register one or many directories first.
```php
jaxon()->di()->getViewManager()->addNamespace('myns', '/path/to/namespace', '.php');
```

You can then use the templates in your classes.
```php
$html = jaxon()->view()->render('myns::path/to/view', ['count' => 5, 'current' => 1]);
```
will render the file `/path/to/namespace/path/to/view.php` file.
