### ISSUE TITLE
Problem with calling registered functions

### ISSUE THREAD

**Issue by nevtag** [jaxon-php/jaxon-core#9]
If I call a registered function nothing happens. With the old xajax it is working.
I register the function on this way.
>$this->jaxon->register(Jaxon::USER_FUNCTION, array('appaction', $this, 'appaction') );

and jaxon write it right in the js.

>jaxon_appaction = function() {
    return jaxon.request(
        { jxnfun: 'appaction' },
        { parameters: arguments }
    );
};

My firephp output:

>   JAXON::__construct()
Application::__construct()
USER::__construct()
Application::__construct() -> jaxon->processRequest();

But the Request will not be processed.
My question is, must I change my application to the namespace model, so jaxon can call my function?
Or should I go step by step through the Jaxon classes,with firephp , to find out why my function not called?

regards,
Joc

**Comment by feuzeu** [comment]
There is no call to the register() function in the firephp output.
Your Jaxon function shall also be registered when processing the Ajax request.

**Comment by nevtag** [comment]
Post parameters of request
>xjxfun=user_action&jxnr=1481880498385&jxnargs[]=Sdefault&jxnargs[]=Suser

firephp output
>Jaxon\Jaxon::__construct
Jaxon\Plugin\Manager::__construct
Jaxon\Request\Manager::__construct
**Application::__construct**
Jaxon\Jaxon::register(UserFunction,Array)
Jaxon\Jaxon::register $nArgs:2
Jaxon\Jaxon::register $aArgs:Array - $aArgs[0]:UserFunction - $aArgs[1][0]:appaction
Jaxon\Plugin\Manager::register
Jaxon\Request\Request::__construct
**group::__construct**
Jaxon\Jaxon::register(UserFunction,Array)
Jaxon\Jaxon::register $nArgs:2
Jaxon\Jaxon::register $aArgs:Array - $aArgs[0]:UserFunction - $aArgs[1][0]:saveGroupData
Jaxon\Plugin\Manager::register
Jaxon\Request\Request::__construct
**user::__construct**
Jaxon\Jaxon::register(UserFunction,Array)
Jaxon\Jaxon::register $nArgs:2
Jaxon\Jaxon::register $aArgs:Array - $aArgs[0]:UserFunction - $aArgs[1][0]:user_action
Jaxon\Plugin\Manager::register
Jaxon\Request\Request::__construct
**Text::__construct**
Jaxon\Jaxon::register(UserFunction,Array)
Jaxon\Jaxon::register $nArgs:2
Jaxon\Jaxon::register $aArgs:Array - $aArgs[0]:UserFunction - $aArgs[1][0]:text_action
Jaxon\Plugin\Manager::register
Jaxon\Request\Request::__construct
**location::__construct**
Jaxon\Jaxon::register(UserFunction,Array)
Jaxon\Jaxon::register $nArgs:2
Jaxon\Jaxon::register $aArgs:Array - $aArgs[0]:UserFunction - $aArgs[1][0]:location_action
Jaxon\Plugin\Manager::register
Jaxon\Request\Request::__construct
**Application::__construct -->> jaxon->processRequest();**
Jaxon\Jaxon::processRequest
Jaxon\Jaxon::canProcessRequest
Jaxon\Plugin\Manager::canProcessRequest
Jaxon\Jaxon::processRequest->canProcessRequest() returns 0

The Request can't be processed.

**Comment by nevtag** [comment]
I think I find it.

**xjxfun**=user_action&jxnr=1481880498385&jxnargs[]=Sdefault&jxnargs[]=Suser

jaxon_appaction = function() {
return jaxon.request(
{ **jxnfun**: 'appaction' },
{ parameters: arguments }
);
};

You changed **xjxfun** to **jxfun**.
A small but fine difference.
Will change it and see if it's working.

**Comment by nevtag** [comment]
No, that wasn't the trick. Same result.

**Comment by nevtag** [comment]
Yes, that was it.
It make sense to write a note in "Migrating from Xajax to Jaxon" on jaxon-php.org, that users must change the direct javascript calls.
I make calls like this
>jaxon.request( { jxnfun: 'text_action' }, { parameters: ['remove',id] }, { mode: 'synchronous' })

**Comment by feuzeu** [comment]
Users are not supposed to make this kind of direct call, since they are wrapped in the generated javascript functions.
The register() functions provide a standard mechanism to add parameters to Ajax calls. That's the way things should be done, and if it does not work, then an issue should be created here.

**Comment by nevtag** [comment]
The generated javascript functions do not what I need. That was already at xajax.
And I did not use the generated functions.
I have for each class a public base function, this function is the only one who I register. All other functions of the class are called by this function. I do this because I have had dozens of registered functions in the past, now I have a hand full. And for each request I must decide is it a synchron or asynchron one.
I think this is a special requirement only for me. A solution can be to make a synch and asynch function and register both.

**Comment by feuzeu** [comment]
The third parameter of the register() function can be used to add parameters to the generated javascript calls. It is the preferred method to set a subset of ajax calls as synchronous.
For a function, this is how to make a synchronous ajax call.
```
$jaxon->register(Jaxon::USER_FUNCTION, 'myFunction', array('mode' => "'synchronous'"))
```
Note the quotes in the option value.
The following code will be generated
```
jaxon_myFunction = function() {
    return jaxon.request(
        { jxnfun: 'myFunction' },
        { parameters: arguments, mode: 'synchronous' }
    );
};
```
When registering objects, different options can be set for each method.
```
$jaxon->register(Jaxon::CALLABLE_OBJECT, new MyClass(), array(
    'firstMethod' => array('mode' => "'synchronous'"),
    'secondMethod' => array('mode' => "'asynchronous'"),
));
```
Replace the method name whith '*' to set an option for all methods.
```
JaxonMyClass = {};
JaxonMyClass.firstMethod = function() {
    return jaxon.request(
        { jxncls: 'MyClass', jxnmthd: 'firstMethod' },
        { parameters: arguments, mode: 'synchronous' }
    );
};
JaxonMyClass.secondMethod = function() {
    return jaxon.request(
        { jxncls: 'MyClass', jxnmthd: 'secondMethod' },
        { parameters: arguments, mode: 'asynchronous' }
    );
};
```

**Comment by feuzeu** [comment]
If you want to make both synchronous and asynchronous calls on the same function, use the [alias feature](https://www.jaxon-php.org/examples/simple/alias.html) to register the same method in synchronous and asynchronous modes.

**Comment by nevtag** [comment]
After I realize how I did it 8 years ago, I changed the register method and the js call and it's working.
As I have done so far, it has worked very well. So I did not question it.
I take a look back in the old xajax api docs. The alias is well hidden there.
Well, I will cleanup my framework and modernize it on namespace modle and jaxon.
Thank you for the information and your help.

**Comment by jatubio** [comment]
@nevtag Thanks a lot!

I saved a lot of time thanks to your comment about **changed xjxfun to jxnfun**
