### ISSUE TITLE
Jaxon v4 is coming

### ISSUE THREAD

**Issue by feuzeu** [jaxon-php/jaxon-core#90]
Hi All,

I've started working on the v4 releases of the Jaxon library, and this is an overview of the current and upcoming changes.

Any comment, suggestion or question is welcome.

***New features***

Many parts of the library have been rewritten, many classes have been moved and renamed, for more simplicity, readability and performance.

- The DI container has been greatly improved, and is now widely used across the library. For example, there's no more calls to the global `jaxon()` function in the library.
- Interfaces have been defined for request and response plugins, making it easier to understand their features.
- New exception classes are added.
- The event dispatcher is removed.
- Some utility features (translator, templates, config, etc) are moved to the new [jaxon-utils](https://github.com/jaxon-php/jaxon-utils) package.
- There are improvements on the request and response plugin system, the request factory, the upload handler, and the code generator.

The next (and last?) upcoming feature is annotation.
It will allow the developer to define properties of the exported classes together with the classes, using the PHP annotation syntax.

For example, with the following code, Jaxon will upload the files in the HTML input component with id `html_field_id`.

```php
    /**
     * Save the uploaded files
     * 
     * @upload(field="html_field_id")
     *
     * @return Response
     */
    public function saveFiles()
    {
        $files = jaxon()->upload()->files();
        // Process the uploaded files.
    }
```

Annotations will be defined for all the options of class registration, and maybe also for validation.

***Breaking changes***

For now, these are the three breaking changes, and I think they will be no new one.

1. The `Response` object.

Instantiating the `Response` class will not work anymore, since its constructor now takes parameters. The `Jaxon` class must be used to create response objects.
Before
```php
$response = new Response();
```
After
```php
$response = jaxon()->newResponse();
```
It is still recommended to use the global response object.
```php
$response = jaxon()->getResponse();
```

2. The plugin registration.

The request and response plugins must now be registered by class name, and not by instance.
Before
```php
jaxon()->registerPlugin(new Plugin());
```
After
```php
// The second parameter must be the same value as returned by the getName() method of the plugin class.
jaxon()->registerPlugin(Plugin::class, 'name');
```
By default, the plugin instance will be created using the `auto()` method of the Jaxon DI, allowing the constructor to take any object registered in the DI as parameter. Optionally, the DI can be explicitely set for the plugin class, before the registration.
```php
jaxon()->di()->set(Plugin::class, function($c) {
    // Create and return an instance of the Plugin class.
});
jaxon()->registerPlugin(Plugin::class, 'name');
```

Additionally, the `canProcessRequest()` method of the request plugin interface is now static, so it can be called without creating an instance of the class. Only the request plugin that will actually process the current request will be instantiated.

3. The integration plugins

The interface for integration plugin is now simpler.
The `processRequest()` method is removed from the `Jaxon\App\AppTrait` trait, and many other methods are added to define views, session manager, logger and container, makig it easier to define new plugins.

**Comment by feuzeu** [comment]
Hi all,

One feature that has just been added to this library, and which unfortunately I did not list in the above message, is the PSR7 and PSR15 support.
Jaxon is now able to handle input HTTP requests and return HTTP responses as defined by the PSR7 message interfaces. It also provides PSR15 middlewares and request handlers, making it easy to integrate with PHP frameworks or CMSs that support these standards.

**Comment by feuzeu** [comment]
Hi,

I've published demo packages for framework integration with Jaxon, which are easier to install and run than the previous ones.

- Symfony: https://github.com/jaxon-php/jaxon-demo-symfony
- Laravel: https://github.com/jaxon-php/jaxon-demo-laravel
- CakePHP: https://github.com/jaxon-php/jaxon-demo-cakephp
- Slim: https://github.com/jaxon-php/jaxon-demo-slim
- Yii: https://github.com/jaxon-php/jaxon-demo-yii
- CodeIgniter: https://github.com/jaxon-php/jaxon-demo-codeigniter

**Comment by feuzeu** [comment]
Hi,

I decided to add a new feature that was not initially planned on this new release.

The upload feature is moved to a separate package https://github.com/jaxon-php/jaxon-upload, and will now use the PHP League Flysytem package https://flysystem.thephpleague.com/docs/ to store uploaded files.

It will allow to store the uploaded files to various storage systems, in addition to the local disk.

Following this change, the upload feature will be disabled by default on the core package.

**Comment by kskelton2021** [comment]
hi, im trying to get up and running with Jaxon v4 however i can't find documentation on the changes that would allow me to migrate from v3 to v4. My server is being upgraded to PHP8 and v4 seems to be the only version of jaxon that will work properly with PHP8.

Can you point me in the right direction to get things going?

<?php
require (TPS_DIR . '/jaxon/4.1.0/autoload.php'); //Jaxon API

use Jaxon\Jaxon;

$jaxon = jaxon();
$jaxon->setOption('core.debug.on', 0);

//Registered Classes
$jaxon->register(Jaxon::CALLABLE_CLASS, PLTMGenerator::class, [
	'include' => ROOT_DIR . '/classes/Jax/PLTMGenerator.class.php'
]);

if($jaxon->canProcessRequest()){
    $jaxon->processRequest();
}

My class file looks like this:

<?php
use Jaxon\Response\Response;

class PLTMGenerator extends DBase {
     public function gen_hp_summary() {
          $response = new Response();

          [My coding here]
		
	  $response->assign('div2', 'innerHTML', 'Data Updated!');
     return $response;
     }
}

To access the function, i click the following link:

<li class="nav-item" id="div2"><a class="nav-link" href="#" onclick="JaxonPLTMGenerator.gen_hp_summary(); return false;">Generator</a></li>

Any help will be greatly appreciated.

Thanks.
