### ISSUE TITLE
Jaxon website has expired ssl certificate

### ISSUE THREAD

**Issue by simplexx** [jaxon-php/jaxon-core#99]
Hey, fantastic project, thanks a lot for your work! I noticed the jaxon website (https://www.jaxon-php.org/) has an expired ssl certificate since 2 days ago, which causes some browsers to display a warning message when visiting. Just wanted to let you know. Cheers.

**Comment by feuzeu** [comment]
Hi,
The issue is fixed. Sorry for the convenience.
